#!/usr/bin/env python3
"""generate-harnesses.py — derive per-harness docs + covered status from the registry.

WHY THIS EXISTS: the fleet may need ~100 coding-agent harnesses wired to the
cortex context store. At that scale the failure mode is not missing docs — it is
**100 docs that disagree with each other and with reality**. So nothing per-harness
is hand-written: `ops/install/harnesses/registry.yaml` is the single source, and
this generator derives each harness's README from it.

    generate-harnesses.py              write/refresh every derived file
    generate-harnesses.py --check      exit 1 if any derived file is stale (CI/doctor)
    generate-harnesses.py --report     coverage summary: declared vs actually wired
    generate-harnesses.py --add <name> --layer mcp --surface '...'
                                       scaffold a NEW registry entry (then fill why/install/verify)

Adding harness #37 is therefore: one registry entry (+ a bespoke artifact only if
the layer demands one), then `--check` proves every derived file agrees.

Design: docs/design/cortex-memory-session-mcp.md
Runbook: docs/runbooks/context-integration.md
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - PyYAML is present in the fleet
    print("generate-harnesses: PyYAML required (pip install pyyaml)", file=sys.stderr)
    sys.exit(1)

HERE = Path(__file__).resolve().parent
REGISTRY = HERE / "registry.yaml"

# Generated files carry this banner: a hand-edit is a bug, because the next
# --check would flag it and the next generate would erase it.
BANNER = ("<!-- GENERATED by ops/install/harnesses/generate-harnesses.py "
          "from registry.yaml — do NOT edit by hand. -->")

LAYER_NOTES = {
    "mcp": ("This harness reads MCP servers from its own configuration, so it needs "
            "**no shim**. Registration is a config entry."),
    "cli-extension": ("This harness has **no MCP client**. It reaches the shared CLI "
                      "through the extension shipped in this directory."),
    "cli-hook": ("This harness needs only a lifecycle command run at a boundary — "
                 "the shared trigger, no tool surface."),
    "none": ("**Not supported (and deliberately declared, not silently missing).** "
             "See *why* — a guessed layer produces a wiring that exists and does nothing."),
}

STATUS_ORDER = {"shipped": 0, "documented": 1, "blocked": 2, "planned": 3}


def load_registry() -> dict:
    if not REGISTRY.is_file():
        print(f"generate-harnesses: registry not found at {REGISTRY}", file=sys.stderr)
        sys.exit(1)
    with REGISTRY.open() as fh:
        try:
            data = yaml.safe_load(fh) or {}
        except yaml.YAMLError as exc:
            # A traceback here would be useless to the agent who just broke it;
            # name the file and the position so it is a one-line fix.
            print(f"generate-harnesses: registry is not valid YAML — fix it before "
                  f"anything else can run.\n  {REGISTRY}\n  {exc}", file=sys.stderr)
            sys.exit(1)
    if not isinstance(data.get("harnesses"), list) or not data["harnesses"]:
        print("generate-harnesses: registry has no 'harnesses:' list", file=sys.stderr)
        sys.exit(1)
    return data


def validate(data: dict) -> list[str]:
    """Registry errors must be loud: a malformed entry silently drops a harness."""
    problems = []
    seen = set()
    for i, h in enumerate(data["harnesses"]):
        where = f"harnesses[{i}]"
        name = h.get("name")
        if not name:
            problems.append(f"{where}: missing 'name'")
            continue
        where = f"harnesses[{i}] ({name})"
        if name in seen:
            problems.append(f"{where}: duplicate name")
        seen.add(name)
        layer = h.get("layer")
        if layer not in LAYER_NOTES:
            problems.append(f"{where}: layer '{layer}' not one of {sorted(LAYER_NOTES)}")
        if not h.get("why"):
            problems.append(f"{where}: missing 'why' (the reason the layer is right)")
        if layer != "none":
            if not h.get("surface"):
                problems.append(f"{where}: missing 'surface' (what you wire against)")
            if not h.get("install"):
                problems.append(f"{where}: missing 'install'")
            if not h.get("verify"):
                problems.append(f"{where}: missing 'verify' — an unverifiable "
                                "instruction is how a wiring ships broken")
        if layer == "cli-extension" and not h.get("artifact"):
            problems.append(f"{where}: layer cli-extension needs 'artifact'")
        if layer == "cli-extension" and h.get("artifact"):
            p = HERE / name / h["artifact"]
            if not p.is_file():
                problems.append(f"{where}: artifact missing on disk: {p}")
    return problems


def derived_run_line(h: dict) -> str | None:
    """The harness's run command, with the tool allowlist DERIVED.

    Pi's mem_*/session_* half of `--tools` must never be hand-typed in the
    registry: a literal silently rots when `context_tools.TOOLS` grows, and the
    harness then cannot reach a tool that plainly exists (the exact drift
    `tests/test_context_harnesses.py` exists to catch). So the one generator both
    the docs and `hc harness install` agree on is `ops/scripts/hc/harness.py`.
    """
    if h.get("run"):
        return h["run"].strip()
    if h.get("layer") != "cli-extension" or not h.get("tools_base"):
        return None
    harness_py = next((p for p in [
        HERE.parent.parent / "scripts" / "hc" / "harness.py",          # repo: ops/scripts/hc
        Path.home() / "hermes-cortex" / "ops" / "scripts" / "hc" / "harness.py",
        Path.home() / ".hermes-cortex" / "scripts" / "hc" / "harness.py",  # deployed
    ] if p.is_file()), None)
    if harness_py is None:
        return None
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location("hc_harness_for_gen", harness_py)
        if spec is None or spec.loader is None:
            return None
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return mod.derived_run_line(h)[0]
    except Exception:
        return None


def render_readme(reg: dict, h: dict) -> str:
    defaults = reg.get("defaults", {})
    name, layer = h["name"], h["layer"]
    out = [BANNER, "", f"# {name} — cortex context integration", ""]
    out += [f"**Layer:** `{layer}`  ·  **Status:** `{h.get('status', 'planned')}`  ·  "
            f"**Surface:** `{h.get('surface', 'n/a')}`", ""]
    out += [LAYER_NOTES[layer], ""]
    out += ["## Why this layer", "", h["why"].strip(), ""]

    if h.get("artifact"):
        out += ["## Shipped artifact", "",
                f"`ops/install/harnesses/{name}/{h['artifact']}`", ""]

    if h.get("triggers"):
        out += ["## Lifecycle triggers (the half MCP cannot provide)", "",
                "The harness owns **when** a checkpoint is written. Never make the "
                "model responsible for it.", ""]
        for k, v in h["triggers"].items():
            out.append(f"- `{k}` → {v}" if k != "note" else f"- {v}")
        out.append("")

    if h.get("install"):
        out += ["## Install", "", "```bash", h["install"].strip(), "```", ""]
    run = derived_run_line(h)
    if run:
        out += ["## Run", "", "```bash", run, "```", ""]
        if not h.get("run"):
            out += ["The `mem_*`/`session_*` half of `--tools` is **derived from "
                    "the contract** by `hc harness install` — a hand-typed list "
                    "rots silently when the tool surface grows.", ""]

    if h.get("verify"):
        out += ["## Verify (do not report a wiring you have not exercised)", ""]
        out += [f"{i}. {v}" for i, v in enumerate(h["verify"], 1)]
        out.append("")
    elif layer == "none":
        out += ["## Verify", "", "Nothing to verify until the surface is known.", ""]

    envs = defaults.get("env", [])
    optional = defaults.get("env_optional", [])
    if envs or optional:
        out += ["## Session identity", "",
                "One session = one identity. Precedence is identical in every layer "
                "(args → env → git), which is what lets a checkpoint written here be "
                "restored by another harness.", "", "```bash"]
        out += [f"export {e}=<value>" for e in envs]
        out += ["```", ""]
    if optional:
        out += ["Overrides (usually unnecessary, needed on macOS):", "", "```bash"]
        out += [f"export {e}=<path>   # see the failure modes in the runbook" for e in optional]
        out += ["```", ""]

    out += ["## Shared pieces (identical for every harness — never fork them)", "",
            f"- CLI: `{defaults.get('cli_path', 'cortex-context')}`",
            f"- MCP server: `{defaults.get('mcp_server', 'cortex-context-mcp.py')}`",
            f"- Trigger: `{defaults.get('trigger', 'session-autocheckpoint.py')}`",
            f"- One implementation: `{defaults.get('impl', 'ops/services/mycortex-mem/context_tools.py')}`",
            "",
            "Full runbook: [`docs/runbooks/context-integration.md`](../../../docs/runbooks/context-integration.md)",
            ""]
    return "\n".join(out)


def render_index(reg: dict) -> str:
    hs = sorted(reg["harnesses"], key=lambda h: (STATUS_ORDER.get(h.get("status", "planned"), 9),
                                                 h["name"]))
    out = [BANNER, "", "# Harness integration index", "",
           "Generated from `registry.yaml`. **Add a harness by adding a registry "
           "entry**, not by writing a new doc.", "",
           f"Declared harnesses: **{len(hs)}**", "",
           "| Harness | Layer | Status | Surface |", "|---|---|---|---|"]
    for h in hs:
        out.append(f"| `{h['name']}` | `{h['layer']}` | {h.get('status', 'planned')} "
                   f"| `{h.get('surface', 'n/a')}` |")
    out += ["", "## Layer meanings", ""]
    for k, v in LAYER_NOTES.items():
        out.append(f"- **`{k}`** — {v}")
    out += ["", "## Regenerating", "", "```bash",
            "python3 ops/install/harnesses/generate-harnesses.py",
            "python3 ops/install/harnesses/generate-harnesses.py --check   # CI/doctor",
            "```", ""]
    return "\n".join(out)


def derived_files(reg: dict) -> dict[Path, str]:
    files = {HERE / "INDEX.md": render_index(reg)}
    for h in reg["harnesses"]:
        files[HERE / h["name"] / "README.md"] = render_readme(reg, h)
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate per-harness integration docs.")
    ap.add_argument("--check", action="store_true", help="exit 1 if any derived file is stale")
    ap.add_argument("--report", action="store_true", help="coverage summary only")
    ap.add_argument("--add", metavar="NAME", help="scaffold a new registry entry")
    ap.add_argument("--layer", default="mcp", help="layer for --add")
    ap.add_argument("--surface", default="", help="surface for --add")
    a = ap.parse_args()

    reg = load_registry()
    problems = validate(reg)
    if problems:
        print("generate-harnesses: registry problems:", file=sys.stderr)
        for p in problems:
            print(f"  ✗ {p}", file=sys.stderr)
        return 1

    if a.add:
        if any(h["name"] == a.add for h in reg["harnesses"]):
            print(f"generate-harnesses: '{a.add}' is already registered", file=sys.stderr)
            return 1
        entry = (f"\n  - name: {a.add}\n    layer: {a.layer}\n    status: planned\n"
                 f"    surface: '{a.surface or 'TODO — read the harness docs'}'\n"
                 f"    why: |\n      TODO — the evidence for this layer.\n"
                 f"    install: |\n      TODO\n"
                 f"    verify:\n      - 'TODO'\n")
        with REGISTRY.open("a") as fh:
            fh.write(entry)
        print(f"generate-harnesses: scaffolded '{a.add}' — fill in why/install/verify, "
              f"then re-run to generate its files.")
        return 0

    files = derived_files(reg)

    if a.report:
        by_status: dict[str, int] = {}
        for h in reg["harnesses"]:
            by_status[h.get("status", "planned")] = by_status.get(h.get("status", "planned"), 0) + 1
        print(f"declared harnesses: {len(reg['harnesses'])}")
        for k in sorted(by_status, key=lambda s: STATUS_ORDER.get(s, 9)):
            print(f"  {k}: {by_status[k]}")
        print(f"derived files: {len(files)}")
        return 0

    if a.check:
        stale = []
        for path, content in files.items():
            if not path.is_file() or path.read_text() != content:
                stale.append(path)
        if stale:
            print("generate-harnesses: STALE (run the generator):", file=sys.stderr)
            for p in stale:
                print(f"  ✗ {p.relative_to(HERE)}", file=sys.stderr)
            return 1
        print(f"generate-harnesses: OK — {len(files)} derived file(s) current")
        return 0

    written = 0
    for path, content in files.items():
        if not path.is_file() or path.read_text() != content:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            written += 1
    print(f"generate-harnesses: {written} file(s) written, {len(files)} current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
