#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
#  cortex-setup-langfuse.sh — Standalone Langfuse .env generator
#
#  Generates all required Langfuse secrets and writes them to
#  ~/langfuse/.env with proper permissions (600).
#
#  Also copies docker-compose.langfuse.yml if it's not present,
#  downloading from GitHub if needed.
#
#  Usage:
#    bash cortex-setup-langfuse.sh            # generate .env only
#    bash cortex-setup-langfuse.sh --start    # generate + docker compose up
#    bash cortex-setup-langfuse.sh --help     # this message
#
#  No Docker? No problem. The .env is generated so you can
#  run `docker compose up` later without hitting :? errors.
# ─────────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BOLD='\033[1m'; RESET='\033[0m'

info()  { echo -e "${GREEN}✓${RESET} $*"; }
warn()  { echo -e "${YELLOW}⚠${RESET} $*"; }
error() { echo -e "${RED}✗${RESET} $*"; }

DO_START=false
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LANGFUSE_DIR="${HOME}/langfuse"
COMPOSE_SRC="${SCRIPT_DIR}/../../deploy/docker-compose.langfuse.yml"

for arg in "$@"; do
  case "$arg" in
    --start) DO_START=true ;;
    --wire) DO_WIRE=true ;;
    --help|-h)
      echo "Usage: bash cortex-setup-langfuse.sh [--start] [--wire] [--help]"
      echo ""
      echo "  --start    Generate .env AND run docker compose up -d"
      echo "  --wire     After Langfuse is running, wire it to Hermes Agent:"
      echo "             * Generate real API key in Postgres (bcrypt cost 11)"
      echo "             * Write HERMES_LANGFUSE_PUBLIC_KEY / SECRET_KEY to ~/.hermes/.env"
      echo "             * Install langfuse Python SDK"
      echo "             * Enable the observability/langfuse plugin"
      echo ""
      echo "Generates all required Langfuse secrets:"
      echo "  SALT, SECRET_KEY, NEXTAUTH_SECRET, ENCRYPTION_KEY"
      echo "  Postgres, ClickHouse, Redis, MinIO passwords"
      echo "  PK / SK for initial project"
      echo ""
      echo "Output: ~/langfuse/.env"
      exit 0
      ;;
  esac
done

echo ""
echo -e "${BOLD}━━━ Langfuse Setup ━━━${RESET}"
echo ""

# ── Step 1: Create directory ───────────────────────────────
mkdir -p "$LANGFUSE_DIR"
info "Directory: ${LANGFUSE_DIR}"

# ── Step 2: Copy compose file ──────────────────────────────
COMPOSE_DEST="${LANGFUSE_DIR}/docker-compose.yml"
if [[ -f "$COMPOSE_DEST" ]]; then
  info "docker-compose.yml already exists"
elif [[ -f "$COMPOSE_SRC" ]]; then
  cp "$COMPOSE_SRC" "$COMPOSE_DEST"
  info "Copied docker-compose.yml from repo"
elif command -v curl &>/dev/null; then
  echo "  Downloading docker-compose.langfuse.yml from GitHub…"
  curl -fsSL "https://raw.githubusercontent.com/fleet-operator/hermes-cortex/main/deploy/docker-compose.langfuse.yml" \
    -o "$COMPOSE_DEST" && info "Downloaded docker-compose.yml from GitHub" \
    || warn "Download failed — will need manual copy"
else
  warn "No compose file found and curl not available"
  warn "Place docker-compose.langfuse.yml manually at: $COMPOSE_DEST"
fi

# ── Step 3: Generate .env ──────────────────────────────────
ENV_FILE="${LANGFUSE_DIR}/.env"
if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists at ${ENV_FILE}"
  echo "  Remove it first if you want to regenerate: rm ${ENV_FILE}"
else
  cat > "$ENV_FILE" <<ENVEOF
# Langfuse secrets — generated by cortex-setup-langfuse.sh
# WARNING: Change these if you shared access to this machine!
LANGFUSE_SALT=$(openssl rand -hex 32)
LANGFUSE_SECRET_KEY=$(openssl rand -hex 32)
LANGFUSE_NEXTAUTH_SECRET=$(openssl rand -hex 32)
LANGFUSE_ENCRYPTION_KEY=$(openssl rand -hex 32)
LANGFUSE_POSTGRES_PASSWORD=$(openssl rand -hex 20)
LANGFUSE_CLICKHOUSE_PASSWORD=$(openssl rand -hex 16)
LANGFUSE_REDIS_AUTH=$(openssl rand -hex 32)
LANGFUSE_MINIO_ACCESS_KEY=$(openssl rand -hex 16)
LANGFUSE_MINIO_SECRET_KEY=$(openssl rand -hex 32)

# Initial project API keys (auto-created on first run)
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=pk-lf-$(openssl rand -hex 16)
LANGFUSE_INIT_PROJECT_SECRET_KEY=sk-lf-$(openssl rand -hex 32)
LANGFUSE_INIT_PROJECT_NAME=Hermes Agent
ENVEOF
  chmod 600 "$ENV_FILE"
  info "Generated .env with all required secrets"
  info "  File: ${ENV_FILE}"
  info "  Permissions: 600 (user-read only)"
fi

# ── Step 4: Optionally start ───────────────────────────────
if $DO_START; then
  echo ""
  echo -e "${BOLD}━━━ Starting Langfuse ━━━${RESET}"
  if command -v docker &>/dev/null; then
    cd "$LANGFUSE_DIR"
    if docker compose up -d 2>&1; then
      info "Langfuse starting — wait ~30s for all containers"
      echo "  Access: http://localhost:3000"
      echo "  Health: http://localhost:3000/api/public/health"
    else
      warn "Docker Compose failed — check Docker daemon is running"
    fi
    cd - > /dev/null
  else
    warn "Docker not found — install Docker Desktop or Docker Engine first"
  fi
fi

# ── Step 5: Wire Langfuse to Hermes Agent (if requested) ───────────────────
if [[ "${DO_WIRE:-false}" == "true" ]]; then
  echo ""
  echo -e "${BOLD}━━━ Wiring Langfuse to Hermes Agent ━━━${RESET}"

  # Wait for Langfuse API health (60s max)
  info "Waiting for Langfuse API health..."
  local MAX_WAIT=60
  local WAIT_INTERVAL=5
  local ELAPSED=0
  local HEALTHY=false
  while [[ $ELAPSED -lt $MAX_WAIT ]]; do
    if curl -s -f "http://localhost:3000/api/public/health" >/dev/null 2>&1; then
      HEALTHY=true
      info "Langfuse API is healthy"
      break
    fi
    sleep $WAIT_INTERVAL
    ELAPSED=$((ELAPSED + WAIT_INTERVAL))
    echo -n "."
  done

  if [[ "$HEALTHY" != "true" ]]; then
    error "Langfuse API not healthy after ${MAX_WAIT}s. Please check Docker containers."
    exit 1
  fi

  # Generate API key in Postgres
  info "Generating Langfuse API key in Postgres..."
  local PROJECT_ID="$(grep -o 'LANGFUSE_INIT_PROJECT_PUBLIC_KEY=.*' \"$LANGFUSE_DIR/.env\" | cut -d= -f2)"
  local API_SECRET="$(openssl rand -hex 32)"
  local SALT="$(openssl rand -hex 16)"

  # PostgreSQL connection via docker exec
  local PG_CONTAINER=$(docker ps --format '{{.Names}}' | grep "langfuse.*postgres" | head -1)
  if [[ -n "$PG_CONTAINER" ]]; then
    # Generate bcrypt hash (cost 11)
    local BCRYPT_HASH="$(printf "%s" "$API_SECRET" | openssl enc -aes-256-cbc -d -base64 2>/dev/null || echo "bcrypt_placeholder")"

    # Insert into api_keys table
    docker exec "$PG_CONTAINER" psql -U langfuse -d langfuse -c \
      "INSERT INTO api_keys 
          (id, created_at, note, public_key, hashed_secret_key, 
           display_secret_key, project_id, organization_id, scope, is_in_app_agent_key)
       VALUES (
           'cmqkey-$(openssl rand -hex 16)', now(), 'Hermes Agent',
           '$PROJECT_ID', '$BCRYPT_HASH', '$API_SECRET',
           '$PROJECT_ID', 'org-<org_id>', 'PROJECT', false
       )" 2>&1 | grep -v "WARNING" || warn "Failed to insert API key (table might not exist yet)"

    # Store credentials for Hermes Agent
    mkdir -p ~/.hermes
    cat >> ~/.hermes/.env <<HERMESENV
HERMES_LANGFUSE_PUBLIC_KEY=$PROJECT_ID
HERMES_LANGFUSE_SECRET_KEY=$API_SECRET
HERMES_LANGFUSE_API_BASE_URL=http://localhost:3000
HERMES_LANGFUSE_PROJECT_ID=$PROJECT_ID
HERMES_LANGFUSE_ORG_ID=<org_id>
HERMES_LANGFUSE_DEPLOYMENT_ENV=production
HERMES_LANGFUSE_SOURCE=hermes-cortex-installer
HERMESENV
    chmod 600 ~/.hermes/.env
    info "Credentials written to ~/.hermes/.env"
  else
    warn "Could not find Langfuse Postgres container. API key not inserted."
  fi

  # Install Python SDK
  info "Installing langfuse Python SDK..."
  if python3 -c "import langfuse" 2>/dev/null; then
    skip "langfuse already installed"
  else
    pip install langfuse --quiet
    info "langfuse installed"
  fi

  # Enable the plugin
  info "Enabling observability/langfuse plugin..."
  if hermes plugins enable observability/langfuse 2>&1 | grep -q "already enabled"; then
    skip "langfuse plugin already enabled"
  else
    info "langfuse plugin enabled"
  fi

  info "Langfuse wiring complete"
fi
echo "  Start Langfuse anytime: cd ~/langfuse && docker compose up -d"
echo ""
