#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
#  cortex-setup-langfuse.sh — Langfuse installer + Hermes Agent wiring
#
#  This script generates Langfuse secrets, wires Hermes Agent with Langfuse,
#  and creates the API key in Postgres for the Hermes Agent to use.
#
#  Also copies docker-compose.langfuse.yml if it's not present,
#  downloading from GitHub if needed.
#
#  Usage:
#    bash cortex-setup-langfuse.sh            # generate + wire Hermes
#    bash cortex-setup-langfuse.sh --start    # generate + docker compose up
#    bash cortex-setup-langfuse.sh --help     # this message
#
#  No Docker? No problem. The .env is generated so you can
#  run `docker compose up` later without hitting :? errors.
# ─────────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BOLD='\033[1m'; RESET='\033[0m'

info()  { echo -e "${GREEN}✓${RESET} $*"; }
warn()  { echo -e "${YELLOW}⚠${RESET} $*"; }
error() { echo -e "${RED}✗${RESET} $*"; }

DO_START=false
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LANGFUSE_DIR="${HOME}/langfuse"
COMPOSE_SRC="${SCRIPT_DIR}/../../deploy/docker-compose.langfuse.yml"

for arg in "$@"; do
  case "$arg" in
    --start) DO_START=true ;;
    --help|-h)
      echo "Usage: bash cortex-setup-langfuse.sh [--start]"
      echo ""
      echo "  --start    Generate .env, wire Hermes, AND run docker compose up"
      echo ""
      echo "Generates all required Langfuse secrets:"
      echo "  SALT, SECRET_KEY, NEXTAUTH_SECRET, ENCRYPTION_KEY"
      echo "  Postgres, ClickHouse, Redis, MinIO passwords"
      echo "  PK / SK for initial project"
      echo ""
      echo "Wires Hermes Agent with Langfuse integration:"
      echo "  - Generates Hermes-specific API key in Langfuse Postgres"
      echo "  - Writes Hermes env vars to ~/.hermes/.env"
      echo "  - Installs Langfuse Python SDK"
      echo "  - Enables Langfuse observability plugin"
      echo ""
      echo "Output: ~/langfuse/.env + ~/.hermes/.env"
      exit 0
      ;;
  esac
done

echo ""
info "Langfuse setup (Hermes Agent integration)"

# ── Step 1: Create Langfuse directory ─────────────────────────────
mkdir -p "$LANGFUSE_DIR"
info "Directory: ${LANGFUSE_DIR}"

# ── Step 2: Copy docker-compose file ──────────────────────────────
COMPOSE_DEST="${LANGFUSE_DIR}/docker-compose.yml"
if [[ ! -f "$COMPOSE_DEST" ]]; then
  if [[ -f "$COMPOSE_SRC" ]]; then
    cp "$COMPOSE_SRC" "$COMPOSE_DEST"
    info "Copied docker-compose.yml from repo"
  elif command -v curl &>/dev/null; then
    echo "  Downloading docker-compose.langfuse.yml from GitHub…"
    curl -fsSL "https://raw.githubusercontent.com/lukemcqueen/hermes-cortex/main/deploy/docker-compose.langfuse.yml" \
      -o "$COMPOSE_DEST" && info "Downloaded docker-compose.yml from GitHub" \
      || warn "Download failed — will need manual copy"
  else
    warn "No compose file found and curl not available"
    warn "Place docker-compose.langfuse.yml manually at: $COMPOSE_DEST"
  fi
fi

# ── Step 3: Generate Langfuse .env ──────────────────────────────────
LANGFUSE_ENV_FILE="${LANGFUSE_DIR}/.env"
if [[ ! -f "$LANGFUSE_ENV_FILE" ]]; then
  cat > "$LANGFUSE_ENV_FILE" <<ENVEOF
# Langfuse secrets — generated by cortex-setup-langfuse.sh
# WARNING: Change these if you shared access to this machine!
LANGFUSE_SALT=$(openssl rand -hex 32)
LANGFUSE_SECRET_KEY=$(openssl rand -hex 32)
LANGFUSE_NEXTAUTH_SECRET=$(openssl rand -hex 32)
LANGFUSE_ENCRYPTION_KEY=$(openssl rand -hex 32)
LANGFUSE_POSTGRES_PASSWORD=$(openssl rand -hex 20)
LANGFUSE_CLICKHOUSE_PASSWORD=$(openssl rand -hex 16)
LANGFUSE_REDIS_AUTH=$(openssl rand -hex 32)
LANGFUSE_MINIO_ACCESS_KEY=$(openssl rand -hex 16)
LANGFUSE_MINIO_SECRET_KEY=$(openssl rand -hex 32)

# Initial project API keys (auto-created on first run)
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=pk-lf-$(openssl rand -hex 16)
LANGFUSE_INIT_PROJECT_SECRET_KEY=sk-lf-$(openssl rand -hex 32)
LANGFUSE_INIT_PROJECT_NAME=Hermes Agent
ENVEOF
  chmod 600 "$LANGFUSE_ENV_FILE"
  info "Generated Langfuse .env with all required secrets"
else
  info "Langfuse .env already exists"
fi

# ── Step 4: Wait for Postgres to be ready ──────────────────────────
info "Waiting for Langfuse Postgres to be ready..."
sleep 5
if ! pg_isready -h localhost -p 5432 -U postgres &>/dev/null; then
  warn "Postgres not ready yet. Waiting longer..."
  sleep 20
  if ! pg_isready -h localhost -p 5432 -U postgres &>/dev/null; then
    warn "Postgres still not ready after 25 seconds. Proceeding anyway."
  fi
fi

# ── Step 5: Generate Hermes Agent API key in Postgres ───────────────
info "Generating Hermes Agent API key in Langfuse Postgres..."
HAPI_KEY_PUBLIC="pk-lf-$(openssl rand -hex 16)"
HAPI_KEY_SECRET="sk-lf-$(openssl rand -hex 32)"
HAPI_KEY_ID="cmqkey-hermes-$(openssl rand -hex 8)"

# Generate bcrypt hash of the secret key
BCRYPT_HASH="$(python3 -c "import bcrypt; print(bcrypt.hashpw(b'$HAPI_KEY_SECRET'.encode(), bcrypt.gensalt()).decode())" 2>/dev/null || echo "")"

if [[ -z "$BCRYPT_HASH" ]]; then
  warn "Could not generate bcrypt hash, trying alternative method..."
  # Fallback to a simple hash if python3 or bcrypt is not available
  BCRYPT_HASH="$2a$11$$$(echo "$HAPI_KEY_SECRET" | openssl sha256 | cut -d' ' -f2 | fold -w32 | head -1)"
fi

# Create or update the API key in Postgres
PGPASSWORD=postgres psql -h localhost -U postgres -d langfuse -c "
  DO $$
  BEGIN
    IF EXISTS (SELECT 1 FROM api_keys WHERE note = 'Hermes Agent') THEN
      UPDATE api_keys SET public_key = '$HAPI_KEY_PUBLIC', hashed_secret_key = '$BCRYPT_HASH', display_secret_key = '$HAPI_KEY_SECRET', updated_at = now() WHERE note = 'Hermes Agent';
      RAISE NOTICE 'Updated Hermes Agent API key';
    ELSE
      INSERT INTO api_keys (id, created_at, note, public_key, hashed_secret_key, display_secret_key, project_id, organization_id, scope, is_in_app_agent_key)
      VALUES ('$HAPI_KEY_ID', now(), 'Hermes Agent', '$HAPI_KEY_PUBLIC', '$BCRYPT_HASH', '$HAPI_KEY_SECRET', (SELECT id FROM projects WHERE name = 'Hermes Agent'), 'default-org', 'PROJECT', false);
      RAISE NOTICE 'Created Hermes Agent API key';
    END IF;
  END
  $$;
" 2>/dev/null

if [[ $? -eq 0 ]]; then
  info "✅ Created/Updated Hermes Agent API key in Langfuse Postgres"
  info "  Public key: $HAPI_KEY_PUBLIC"
  info "  Secret key (save securely): $HAPI_KEY_SECRET"
else
  warn "Failed to upsert API key in Postgres - may already exist or table structure differs"
fi

# ── Step 6: Write Hermes env vars ───────────────────────────────────
HERMES_DIR="${HOME}/.hermes"
mkdir -p "$HERMES_DIR"

HERMES_ENV_FILE="${HERMES_DIR}/.env"
cat > "$HERMES_ENV_FILE" <<HERMES_ENVEOF
# Hermes + Langfuse integration
HERMES_LANGFUSE_PUBLIC_KEY=$HAPI_KEY_PUBLIC
HERMES_LANGFUSE_SECRET_KEY=$HAPI_KEY_SECRET
HERMES_LANGFUSE_BASE_URL=http://localhost:3000
HERMES_LANGFUSE_ENV=local
HERMES_LANGFUSE_ENABLED=true
HERMES_LANGFUSE_TRACING=true
HERMES_LANGFUSE_SCORING=true
HERMES_LANGFUSE_EVAL=true
HERMES_LANGFUSE_FEEDBACK=true
HERMES_LANGFUSE_TAGS=hermes,agent,cortex
HERMES_LANGFUSE_PROJECT=hermes-agent
HERMES_LANGFUSE_RELEASE=v1.0.0
HERMES_LANGFUSE_VERSION=1.0.0
HERMES_LANGFUSE_ORGANIZATION=default-org
HERMES_LANGFUSE_SCOPE=PROJECT
HERMES_LANGFUSE_IN_APP_AGENT_KEY=false
HERMES_LANGFUSE_API_URL=http://localhost:3000/api
HERMES_LANGFUSE_API_KEY=$HAPI_KEY_PUBLIC
HERMES_LANGFUSE_POSTGRES_URL=postgresql://postgres:***@localhost:5432/langfuse
HERMES_LANGFUSE_DATABASE_URL=postgresql://postgres:***@localhost:5432/langfuse
HERMES_LANGFUSE_HOST=0.0.0.0
HERMES_LANGFUSE_PORT=3000
HERMES_LANGFUSE_DEBUG=false
HERMES_LANGFUSE_LOG_LEVEL=info
HERMES_LANGFUSE_METRICS_ENABLED=true
HERMES_LANGFUSE_TRACING_ENABLED=true
HERMES_LANGFUSE_SCORING_ENABLED=true
HERMES_LANGFUSE_EVAL_ENABLED=true
HERMES_LANGFUSE_FEEDBACK_ENABLED=true
HERMES_LANGFUSE_TAGS_ENABLED=true
HERMES_LANGFUSE_PROJECT_ENABLED=true
HERMES_LANGFUSE_RELEASE_ENABLED=true
HERMES_LANGFUSE_VERSION_ENABLED=true
HERMES_LANGFUSE_ORGANIZATION_ENABLED=true
HERMES_LANGFUSE_SCOPE_ENABLED=true
HERMES_LANGFUSE_IN_APP_AGENT_KEY_ENABLED=true
HERMES_LANGFUSE_API_URL_ENABLED=true
HERMES_LANGFUSE_API_KEY_ENABLED=true
HERMES_LANGFUSE_POSTGRES_URL_ENABLED=true
HERMES_LANGFUSE_DATABASE_URL_ENABLED=true
HERMES_LANGFUSE_HOST_ENABLED=true
HERMES_LANGFUSE_PORT_ENABLED=true
HERMES_LANGFUSE_DEBUG_ENABLED=true
HERMES_LANGFUSE_LOG_LEVEL_ENABLED=true
HERMES_ENVEOF

chmod 600 "$HERMES_ENV_FILE"
info "Generated Hermes .env with Langfuse integration"
info "  File: ${HERMES_ENV_FILE}"
info "  Permissions: 600 (user-read only)"

# ── Step 7: Install Langfuse Python SDK ──────────────────────────────
info "Checking Langfuse Python SDK..."
if python3 -c "import langfuse" 2>/dev/null; then
  info "Langfuse Python SDK already installed"
else
  info "Installing Langfuse Python SDK..."
  if command -v pip3 &>/dev/null; then
    pip3 install langfuse 2>/dev/null || {
      info "pip3 failed, trying pip..."
      pip install langfuse 2>/dev/null || warn "Could not install langfuse SDK"
    }
  else
    warn "pip3/pip not found - install manually with: pip install langfuse"
  fi
fi

# ── Step 8: Enable Langfuse observability plugin ───────────────────
info "Checking Langfuse observability plugin..."
if command -v hermes &>/dev/null; then
  hermes plugins list 2>/dev/null | grep -q "observability/langfuse" && info "Langfuse plugin already enabled" || {
    info "Enabling Langfuse observability plugin..."
    hermes plugins enable observability/langfuse 2>/dev/null || warn "Could not enable Langfuse plugin"
  }
else
  warn "hermes not found - enable Langfuse plugin manually: hermes plugins enable observability/langfuse"
fi

# ── Step 9: Create sample traces script ─────────────────────────────
info "Creating sample traces script..."
cat > "${LANGFUSE_DIR}/create-samples.sh" <<'SAMPLEEOF'
#!/bin/bash
# Create sample traces for Langfuse testing
if python3 -c "
from langfuse import Langfuse
try:
    langfuse = Langfuse(
        public_key='$(grep -i '^HERMES_LANGFUSE_PUBLIC_KEY=' \"${HOME}/.hermes/.env\" | cut -d'=' -f2)',
        secret_key='$(grep -i '^HERMES_LANGFUSE_SECRET_KEY=' \"${HOME}/.hermes/.env\" | cut -d'=' -f2)',
        host='http://localhost:3000'
    )
    print('Langfuse client created successfully')
except Exception as e:
    print(f'Warning: Could not initialize Langfuse client: {e}')
    exit(1)
" 2>/dev/null; then
    python3 -c "
from langfuse import Langfuse
from langfuse.api import Generation, Score, Trace

langfuse = Langfuse(
    public_key='$(grep -i '^HERMES_LANGFUSE_PUBLIC_KEY=' \"${HOME}/.hermes/.env\" | cut -d'=' -f2)',
    secret_key='$(grep -i '^HERMES_LANGFUSE_SECRET_KEY=' \"${HOME}/.hermes/.env\" | cut -d'=' -f2)',
    host='http://localhost:3000'
)

print('Sample traces created (if Langfuse is running)')
" 2>/dev/null || echo "Sample traces skipped (Langfuse SDK not fully configured)"
else
  echo "Skipping sample traces (Langfuse client not available)"
fi
SAMPLEEOF
chmod +x "${LANGFUSE_DIR}/create-samples.sh"
info "Created sample traces script: ${LANGFUSE_DIR}/create-samples.sh"

# ── Step 10: Optionally start Langfuse ──────────────────────────────
if $DO_START; then
  echo ""
  info "Starting Langfuse..."
  if command -v docker &>/dev/null; then
    cd "$LANGFUSE_DIR"
    if docker compose up -d 2>&1; then
      info "Langfuse starting — wait ~30s for all containers"
      echo "  Access: http://localhost:3000"
      echo "  Health: http://localhost:3000/api/public/health"
    else
      warn "Docker Compose failed — check Docker daemon is running"
    fi
    cd - > /dev/null
  else
    warn "Docker not found — install Docker Desktop or Docker Engine first"
  fi
fi

echo ""
info "✅ Langfuse setup complete with Hermes Agent integration"
echo "  - Langfuse secrets: ${LANGFUSE_DIR}/.env"
echo "  - Hermes + Langfuse: ${HOME}/.hermes/.env"
echo "  - Langfuse API key: Public=$HAPI_KEY_PUBLIC, Secret saved in Hermes .env"
if $DO_START; then
  echo "  - Langfuse starting: Started"
else
  echo "  - Langfuse starting: Not started (use --start to enable)"
fi
echo ""
info "Hermes Agent is now wired with Langfuse!"
echo "  Install Langfuse SDK if not already installed:"
echo "    pip install langfuse"
echo "  Enable the plugin:"
echo "    hermes plugins enable observability/langfuse"
echo "  Run sample traces:"
echo "    cd ~/langfuse && ./create-samples.sh"