#!/usr/bin/env python3
"""Runnable verification for the absolute-path (repo_path) change — LIVE state.

Adversarial findings ADV-10780-1..6 asked for committed, re-executable evidence
rather than a pasted transcript. This script re-derives every claim in the
delivery note against the CURRENT revision and the DEPLOYED tree, and writes the
full transcript to tests/artifacts/abs-path-live-verification.txt. It exits
non-zero if any structural assertion fails, so the artifact cannot be a stale
green.

Usage:  python3 tests/run_abs_path_live_verification.py
"""
import hashlib
import importlib.util
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ARTIFACT = REPO / "tests" / "artifacts" / "abs-path-live-verification.txt"

DEPLOYED_MCP = Path.home() / ".hermes-cortex" / "tools" / "loop-governance" / "loop-gov-mcp.py"
DEPLOYED_ENFORCER = Path.home() / ".hermes" / "plugins" / "governance-enforcer" / "__init__.py"
REPO_MCP = REPO / "mcp-servers" / "loop-gov-mcp.py"
REPO_ENFORCER = REPO / "plugins" / "governance-enforcer" / "__init__.py"

REGRESSION_TEST = "tests/test_loop_gov_review_repo.py"

# The two commits that landed the deployed-only skill lessons (badbc960,
# de5f058c) and the repo source each one replaced.
DRIFT_COMMITS = [
    ("badbc960", "skills/devops/deploy-load-verification/SKILL.md",
     Path.home() / ".hermes" / "skills" / "devops" / "deploy-load-verification" / "SKILL.md"),
    ("de5f058c", "skills/devops/governance-closeout/SKILL.md",
     Path.home() / ".hermes" / "skills" / "devops" / "governance-closeout" / "SKILL.md"),
]

_HOME = str(Path.home())
_REPO_S = str(REPO)
_PY_BIN = str(Path(sys.executable).parent)

OUT = []
FAILS = []

_HEADER_RE = re.compile(r"^(# SOURCE:.*\n)(# Do NOT edit this file.*\n)\n?", re.M)


def say(line=""):
    OUT.append(line)
    print(line)


def _scrub(text):
    return (text.replace(_REPO_S, "<repo>")
                .replace(_HOME, "~")
                .replace(_PY_BIN, "<python-bin>"))


def _run(argv, cwd=REPO, timeout=300):
    return subprocess.run([str(a) for a in argv], cwd=str(cwd), capture_output=True,
                          text=True, timeout=timeout)


def _git(*args):
    return _run(["git", *args]).stdout.strip()


def _tail(text, n=60):
    lines = [ln for ln in text.rstrip().splitlines() if ln.strip()]
    return "\n".join(lines[-n:])


def _body(path):
    """File content with the deploy's `# SOURCE:` header stripped.

    The deploy INSERTS two comment lines (plus a blank line) after the shebang;
    it does not replace it, so the shebang must survive the strip.
    """
    return _HEADER_RE.sub("", Path(path).read_text(), count=1)


def _md5(text):
    return hashlib.md5(text.encode()).hexdigest()


def _assert(name, cond, detail=""):
    say(f"{'PASS' if cond else 'FAIL'}  {name}" + (f" — {detail}" if detail else ""))
    if not cond:
        FAILS.append(name)


# ── 1. Repo regression test file, re-run live ────────────────────────────────
say("=" * 72)
say("1. REPO REGRESSION — tests/test_loop_gov_review_repo.py re-executed live")
say("=" * 72)
r = _run([sys.executable, REGRESSION_TEST])
say(_scrub(_tail(r.stdout, 60)))
say(f"rc={r.returncode}")
_assert("regression test file rc=0", r.returncode == 0, f"rc={r.returncode}")
_assert("regression test names all present (13)",
        r.stdout.count("test_") >= 13 and "PASS (13)" in r.stdout,
        f"PASS(13)={'PASS (13)' in r.stdout}")
say()

# ── 2. DEPLOYED module, hop by hop (repo copy proves nothing about the deploy) ─
say("=" * 72)
say(f"2. DEPLOYED MODULE — {_scrub(str(DEPLOYED_MCP))} loaded and driven")
say("=" * 72)
tmp = Path(tempfile.mkdtemp(prefix="absprobe-"))
try:
    nested = tmp / "x" / "y" / "proj"           # deeper than a HOME child
    (nested / ".git").mkdir(parents=True, exist_ok=True)
    not_a_repo = tmp / "x"
    home_repo = Path.home() / "hermes-cortex"   # slug fallback target, already a repo

    spec = importlib.util.spec_from_file_location("deployed_loop_gov", DEPLOYED_MCP)
    assert spec is not None and spec.loader is not None, f"cannot load {DEPLOYED_MCP}"
    mod = importlib.util.module_from_spec(spec)
    sys.modules["deployed_loop_gov"] = mod
    spec.loader.exec_module(mod)

    _assert("_derive_repo_path accepts an injected nested repo",
            str(mod._derive_repo_path({"repo_path": str(nested)})) == str(nested))
    _assert("_derive_repo_path refuses a non-repo path",
            mod._derive_repo_path({"repo_path": str(not_a_repo)}) is None)
    _assert("_lock_repo prefers repo_path over the slug",
            str(mod._lock_repo({"repo_path": str(nested),
                                "repo_slug": "hermes-cortex"})) == str(nested))
    _assert("_lock_repo keeps the legacy slug-only fallback",
            str(mod._lock_repo({"repo_slug": "hermes-cortex"})) == str(home_repo))
    _assert("_lock_repo fails closed when neither resolves",
            mod._lock_repo({}) is None)
    _assert("_secondary_lock_path puts the marker inside the nested repo",
            str(mod._secondary_lock_path({"repo_path": str(nested),
                                          "repo_slug": "hermes-cortex"}))
            == str(nested / ".hermes-cortex" / ".governance-lock"))
finally:
    shutil.rmtree(tmp, ignore_errors=True)
say()

# ── 3. Deployed == repo source ───────────────────────────────────────────────
say("=" * 72)
say("3. DEPLOYED == REPO SOURCE")
say("=" * 72)
for label, dep, src in (("loop-gov-mcp.py", DEPLOYED_MCP, REPO_MCP),
                        ("governance-enforcer/__init__.py", DEPLOYED_ENFORCER, REPO_ENFORCER)):
    dep_md5, src_md5 = _md5(_body(dep)), _md5(Path(src).read_text())
    say(f"deployed {label}: md5={dep_md5}  ({Path(dep).stat().st_size} bytes, "
        f"mtime={datetime.fromtimestamp(Path(dep).stat().st_mtime).isoformat(timespec='seconds')})")
    say(f"repo     {label}: md5={src_md5}  ({Path(src).stat().st_size} bytes)")
    _assert(f"deployed matches repo: {label}", dep_md5 == src_md5)
say()

# ── 4. Is the deployed code LOADED? (evidence, not assumption) ───────────────
say("=" * 72)
say("4. LOADED OR ONLY DEPLOYED — process start vs deploy mtime")
say("=" * 72)
deploy_mtime = max(DEPLOYED_MCP.stat().st_mtime, DEPLOYED_ENFORCER.stat().st_mtime)
say(f"deploy mtime (newest of the two deployed files): "
    f"{datetime.fromtimestamp(deploy_mtime).isoformat(timespec='seconds')}")
ps = _run(["ps", "-eo", "pid,lstart,args"])
for ln in ps.stdout.splitlines():
    if ("loop-gov-mcp.py" in ln or "gateway run" in ln) and "grep" not in ln:
        say("  " + " ".join(ln.split()[:7]) + " … " + ln.split()[-1])
say("Verdict: a start time BEFORE the deploy mtime means the new code is on disk but")
say("NOT in memory (MCP child needs a kill; enforcer needs a gateway /reset).")
say()

# ── 5. Liveness witness — the lock file the OLD code wrote ───────────────────
say("=" * 72)
say("5. LIVENESS WITNESS — this session's lock payload")
say("=" * 72)
locks = sorted((Path.home() / ".hermes-cortex" / "state").glob(".governance-*.json"),
               key=lambda p: p.stat().st_mtime)
locks = [p for p in locks if p.stat().st_mtime > deploy_mtime - 86400]
for lock in locks[-3:]:
    text = lock.read_text()
    say(f"  {lock.name}: repo_slug={('repo_slug' in text)}  repo_path={('repo_path' in text)}")
say("A lock written with repo_slug but no repo_path was written by the PREVIOUS revision.")
say()

# ── 6. The two deployed-only skill lessons now live in the repo ──────────────
say("=" * 72)
say("6. SKILL DRIFT — the two deployed-only lessons are in the repo source")
say("=" * 72)
for commit, repo_path, deployed_path in DRIFT_COMMITS:
    before = _run(["git", "show", f"{commit}^:{repo_path}"]).stdout
    after = Path(deployed_path).read_text()
    say(f"  {commit}  {repo_path}")
    say(f"    repo source before sync : {len(before)} bytes")
    say(f"    repo source == deployed : {len(after) == len(Path(REPO / repo_path).read_text())} "
        f"({len(Path(REPO / repo_path).read_text())} bytes)")
    _assert(f"repo source == deployed copy: {repo_path}",
            _md5(Path(REPO / repo_path).read_text()) == _md5(after))
say()

# ── 7. Doctor's own drift check ──────────────────────────────────────────────
say("=" * 72)
say("7. DOCTOR — skill drift count")
say("=" * 72)
doc = _run([sys.executable, "ops/scripts/manage/cortex-doctor.py"], timeout=900)
for ln in doc.stdout.splitlines():
    if "drift" in ln.lower() and "Skill" in ln:
        say(_scrub(ln.strip()))
say()

say("=" * 72)
say(f"RESULT: {'ALL PASS' if not FAILS else 'FAILURES: ' + ', '.join(FAILS)}")
say("=" * 72)

ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
note = (
    "absolute-path (repo_path) change — LIVE verification artifact\n"
    + "=" * 72 + "\n"
    f"generated      : {datetime.now(timezone.utc).isoformat(timespec='seconds')}\n"
    f"revision       : {_git('rev-parse', '--short', 'HEAD')}  (branch {_git('rev-parse', '--abbrev-ref', 'HEAD')})\n"
    f"origin/main    : {_git('rev-parse', '--short', 'origin/main')}\n"
    f"generator      : tests/run_abs_path_live_verification.py\n\n"
    "Re-run with:  python3 tests/run_abs_path_live_verification.py\n\n"
    + _scrub("\n".join(OUT)) + "\n"
)
ARTIFACT.write_text(note)
print(f"\nArtifact written: {ARTIFACT}")
sys.exit(1 if FAILS else 0)
