#!/usr/bin/env python3
"""Hermetic fault-injection suite for agent-deploy-drift-audit (O5-S2).

The drift-audit mirrors cortex_doctor/checks.py's deploy-content + stale-deploy
rules on a schedule (daily, no_agent). This test proves the six behaviours the
doctor check only exercises on-demand:

  A: deployed copy content differs from repo source -> "content drift" alert (exit 1)
  B: orphan .py/.sh in ~/.hermes-cortex/scripts/   -> "stale deploy" alert (exit 1)
  C: registered destination missing on disk        -> "deployed copy missing" alert (exit 1)
  D: register() source missing in repo             -> "deploy source missing" alert (exit 1)
  E: healthy host (header-stripped copies)         -> silent, exit 0
  F: duplicate drift state                         -> silent (StateTracker dedup gate)
  G: intentional symlink to registered path        -> silent (INFO, not an alert)

Run:  python3 tests/test_deploy_drift_audit.py
Optional: DRIFT_AUDIT_PATH=/path/to/agent-deploy-drift-audit.py
"""
import os
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
_env = os.environ.get("DRIFT_AUDIT_PATH")
AUDIT = Path(_env) if _env else (
    REPO / "ops" / "scripts" / "health" / "agent-deploy-drift-audit.py"
)

REGISTER = (
    'register "scripts/foo.sh" "${CORTEX_DEPLOY_HOME}/scripts/foo.sh"\n'
    'register "scripts/bar.py" "${CORTEX_DEPLOY_HOME}/scripts/bar.py"\n'
    'register "scripts/baz.sh" "${CORTEX_DEPLOY_HOME}/scripts/baz.sh"\n'
)
FOO_REPO = "#!/usr/bin/env bash\nset -euo pipefail\necho foo\n"
BAR_REPO = "#!/usr/bin/env python3\nprint('bar')\n"
BAZ_REPO = "#!/usr/bin/env bash\necho baz\n"


def _mkfixture() -> tuple[str, str]:
    """Build a fake repo + deploy home with two healthy register() pairs.

    Deployed copies carry the cortex SOURCE header (new layout: shebang +
    header + blank) and must NOT be flagged — proves header-strip tolerance.
    Returns (fake_repo, fake_deploy_home) with a shared state-dir path used
    for HOME isolation.
    """
    tmp = Path(tempfile.mkdtemp(prefix="drift-audit-test-"))
    repo = tmp / "repo"
    deploy = tmp / "deploy"
    (repo / "ops" / "scripts").mkdir(parents=True)
    (repo / "scripts").mkdir(parents=True)
    (deploy / "scripts").mkdir(parents=True)

    (repo / "ops" / "scripts" / "cortex-update.sh").write_text(REGISTER)
    (repo / "scripts" / "foo.sh").write_text(FOO_REPO)
    (repo / "scripts" / "bar.py").write_text(BAR_REPO)
    (repo / "scripts" / "baz.sh").write_text(BAZ_REPO)

    header = "# SOURCE: scripts/foo.sh\n# Do NOT edit this file — edit the source above and run: bash cortex-update.sh\n\n"
    (deploy / "scripts" / "foo.sh").write_text(f"#!/usr/bin/env bash\n{header}{FOO_REPO.split(chr(10), 1)[1]}")
    (deploy / "scripts" / "bar.py").write_text(BAR_REPO)  # raw copy, no header
    (deploy / "scripts" / "baz.sh").write_text(BAZ_REPO)
    return str(repo), str(deploy)


def _run(repo: str, deploy: str, state_dir: str) -> tuple[int, str]:
    """Run the audit against the fixture; isolate its state file via HOME."""
    env = dict(os.environ)
    env["CORTEX_REPO"] = repo
    env["CORTEX_HOME"] = deploy
    os.makedirs(state_dir, exist_ok=True)
    env["HOME"] = state_dir
    proc = subprocess.run(
        [sys.executable, str(AUDIT)],
        capture_output=True, text=True, env=env, cwd=str(REPO),
    )
    return proc.returncode, proc.stdout.strip()


def main() -> int:
    failures = []
    state = tempfile.mkdtemp(prefix="drift-audit-state-")  # unique per run — stale /tmp state dirs would dedup alerts across runs

    # E: healthy fixture -> silent, exit 0
    repo, deploy = _mkfixture()
    rc, out = _run(repo, deploy, f"{state}/e")
    if rc != 0 or out != "":
        failures.append(f"E healthy silent: rc={rc} out={out!r}")

    # G: intentional symlink (scripts/baz.sh -> registered dest foo.sh) -> silent
    repo, deploy = _mkfixture()
    (Path(deploy) / "scripts" / "baz.sh").unlink()
    (Path(deploy) / "scripts" / "baz.sh").symlink_to(Path(deploy) / "scripts" / "foo.sh")
    rc, out = _run(repo, deploy, f"{state}/g")
    if rc != 0 or out != "":
        failures.append(f"G intentional symlink silent: rc={rc} out={out!r}")

    # A: content drift -> alert
    repo, deploy = _mkfixture()
    (Path(deploy) / "scripts" / "bar.py").write_text("#!/usr/bin/env python3\nprint('DRIFTED')\n")
    rc, out = _run(repo, deploy, f"{state}/a")
    if rc != 1 or "content drift" not in out:
        failures.append(f"A content drift: rc={rc} out={out!r}")

    # B: orphan in scripts dir -> alert
    repo, deploy = _mkfixture()
    (Path(deploy) / "scripts" / "orphan.sh").write_text("#!/usr/bin/env bash\necho orphan\n")
    rc, out = _run(repo, deploy, f"{state}/b")
    if rc != 1 or "stale deploy" not in out:
        failures.append(f"B orphan: rc={rc} out={out!r}")

    # C: registered dest missing -> alert
    repo, deploy = _mkfixture()
    (Path(deploy) / "scripts" / "bar.py").unlink()
    rc, out = _run(repo, deploy, f"{state}/c")
    if rc != 1 or "deployed copy missing" not in out:
        failures.append(f"C dest missing: rc={rc} out={out!r}")

    # D: register source missing in repo -> alert
    repo, deploy = _mkfixture()
    (Path(repo) / "scripts" / "bar.py").unlink()
    rc, out = _run(repo, deploy, f"{state}/d")
    if rc != 1 or "deploy source missing" not in out:
        failures.append(f"D src missing: rc={rc} out={out!r}")

    # F: duplicate drift state -> silent on second run (dedup; same state dir)
    repo, deploy = _mkfixture()
    (Path(deploy) / "scripts" / "bar.py").write_text("#!/usr/bin/env python3\nprint('DRIFTED')\n")
    rc1, _ = _run(repo, deploy, f"{state}/f")
    rc2, out2 = _run(repo, deploy, f"{state}/f")
    if rc1 != 1 or rc2 != 0 or out2 != "":
        failures.append(f"F dedup: rc1={rc1} rc2={rc2} out2={out2!r}")

    if failures:
        print(f"FAIL ({len(failures)}):")
        for f in failures:
            print(f"  - {f}")
        return 1
    print(f"PASS — {AUDIT.name}: 7/7 scenarios (A drift, B orphan, C missing-dest, D missing-src, E healthy, F dedup, G symlink)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
