#!/usr/bin/env python3
"""Hermetic tests for the CONTENT-scoped "Deploy sync" doctor check (2026-10-09).

Why the check changed: it compared the deployed REVISION with local HEAD, so on a
host where several sessions share one checkout a peer's commit touching only
non-deployed paths (docs, evidence, tests) FAILed the check and blocked an
unrelated session's push. Measured three times on esther in one session, each
time with the pusher's own files already deployed and verified.

These cases drive the DETECTOR with controlled inputs — throwaway git repos and
deploy dirs, never the live tree — in both directions:
  * a peer-only commit of unregistered paths      -> PASS (the false positive)
  * a deploy-map file changed and NOT deployed    -> FAIL, naming the file
  * a deploy-map file changed and DEPLOYED        -> PASS, "content-current"
  * a deployed revision that does not resolve     -> WARN could-not-verify (never PASS)
  * a non-deploy-map change committed while the deploy-map file is current -> PASS

Run:  python3 tests/test_doctor_deploy_sync_content_scope.py
"""
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
# checks.py uses relative imports (from .immutability import ...), so it must be
# imported as part of its package — a bare spec_from_file_location fails.
sys.path.insert(0, str(REPO_ROOT / "ops" / "scripts" / "manage"))
import cortex_doctor.checks as checks  # noqa: E402

_FAIL: list = []


def check(name, cond, detail=""):
    if cond:
        print(f"  PASS  {name}")
    else:
        _FAIL.append(name)
        print(f"  FAIL  {name} — {detail}")


class Res:
    """Minimal Results stand-in: records what the check reported."""

    def __init__(self):
        self.entries = []

    def add(self, name, status, detail="", action="", **kw):
        self.entries.append((name, status, str(detail)))

    def deploy_sync(self):
        return [e for e in self.entries if e[0] == "Deploy sync"]


def _git(cwd, *args):
    return subprocess.run(["git", "-C", str(cwd), *args], capture_output=True, text=True)


def _mk_repo(tmp: Path) -> Path:
    repo = tmp / "repo"
    repo.mkdir(parents=True)
    _git(repo, "init", "-q", "-b", "main")
    _git(repo, "config", "user.email", "t@t.t")
    _git(repo, "config", "user.name", "t")
    (repo / "ops" / "scripts").mkdir(parents=True)
    # The register map the check reads: probe.sh -> the deploy home's copy.
    (repo / "ops" / "scripts" / "cortex-update.sh").write_text(
        'register "ops/scripts/probe.sh"  "${CORTEX_DEPLOY_HOME}/scripts/probe.sh"\n')
    (repo / "ops" / "scripts" / "probe.sh").write_text("#!/usr/bin/env bash\necho v1\n")
    (repo / "docs").mkdir()
    (repo / "docs" / "note.md").write_text("first\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "seed")
    return repo


def _setup(tmp: Path, deployed_rev: str, deploy_home: Path):
    checks.CORTEX_REPO = tmp / "repo"
    checks.CORTEX_HOME = deploy_home
    checks.AGENT_ROLE = "orchestrator"
    (deploy_home / "state").mkdir(parents=True, exist_ok=True)
    (deploy_home / "state" / "update-commit").write_text(deployed_rev + "\n")
    (deploy_home / "scripts").mkdir(parents=True, exist_ok=True)


def _deploy_copy(deploy_home: Path, content: str):
    """Write the deployed copy the way the deployer does: banner after the shebang."""
    (deploy_home / "scripts" / "probe.sh").write_text(
        "#!/usr/bin/env bash\n"
        "# SOURCE: /somewhere/ops/scripts/probe.sh\n"
        "# Do NOT edit this file — edit the source above and run: bash cortex-update.sh\n"
        "\n" + content.replace("#!/usr/bin/env bash\n", ""))


def test_peer_only_commit_of_unregistered_paths_passes():
    """THE false positive this change fixes: another session commits a doc; the
    pusher's own deploy-map files are current -> must PASS, not FAIL."""
    tmp = Path(tempfile.mkdtemp(prefix="deploysync-peer-"))
    repo = _mk_repo(tmp)
    deployed = _git(repo, "rev-parse", "HEAD").stdout.strip()
    home = tmp / "deploy"
    _setup(tmp, deployed, home)
    _deploy_copy(home, (repo / "ops" / "scripts" / "probe.sh").read_text())
    # a peer's commit touching only a non-deployed path
    (repo / "docs" / "note.md").write_text("peer edit\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "peer: docs only")

    res = Res()
    checks.check_repo(res)
    entries = res.deploy_sync()
    check("peer-only commit -> Deploy sync reported once", len(entries) == 1, str(entries))
    if entries:
        _n, status, detail = entries[0]
        check("peer-only commit -> PASS", status == "PASS", f"{status}: {detail}")
        check("peer-only commit -> says content-current", "content-current" in detail, detail)


def test_changed_registered_file_not_deployed_fails_and_is_named():
    tmp = Path(tempfile.mkdtemp(prefix="deploysync-stale-"))
    repo = _mk_repo(tmp)
    deployed = _git(repo, "rev-parse", "HEAD").stdout.strip()
    home = tmp / "deploy"
    _setup(tmp, deployed, home)
    _deploy_copy(home, (repo / "ops" / "scripts" / "probe.sh").read_text())
    # the change: probe.sh edited and committed, but the deploy was never refreshed
    (repo / "ops" / "scripts" / "probe.sh").write_text("#!/usr/bin/env bash\necho v2\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "edit probe")

    res = Res()
    checks.check_repo(res)
    entries = res.deploy_sync()
    check("undeployed registered file -> reported once", len(entries) == 1, str(entries))
    if entries:
        _n, status, detail = entries[0]
        check("undeployed registered file -> FAIL", status == "FAIL", f"{status}: {detail}")
        check("undeployed registered file -> named in the detail",
              "ops/scripts/probe.sh" in detail, detail)


def test_changed_registered_file_that_IS_deployed_passes():
    """The other half of the regression: HEAD is ahead of the deployed REVISION, but
    the changed file's deployed copy matches its content -> must PASS."""
    tmp = Path(tempfile.mkdtemp(prefix="deploysync-deployed-"))
    repo = _mk_repo(tmp)
    deployed = _git(repo, "rev-parse", "HEAD").stdout.strip()
    home = tmp / "deploy"
    _setup(tmp, deployed, home)
    (repo / "ops" / "scripts" / "probe.sh").write_text("#!/usr/bin/env bash\necho v2\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "edit probe")
    _deploy_copy(home, (repo / "ops" / "scripts" / "probe.sh").read_text())   # deployed AFTER

    res = Res()
    checks.check_repo(res)
    entries = res.deploy_sync()
    if entries:
        _n, status, detail = entries[0]
        check("deployed content -> PASS", status == "PASS", f"{status}: {detail}")
        check("deployed content -> reports what it checked", "1 checked" in detail, detail)
    else:
        check("deployed content -> reported", False, "no Deploy sync entry")


def test_unresolvable_deployed_revision_is_could_not_verify():
    tmp = Path(tempfile.mkdtemp(prefix="deploysync-unresolvable-"))
    repo = _mk_repo(tmp)
    home = tmp / "deploy"
    _setup(tmp, "0" * 40, home)          # a revision that is not in this repo
    (repo / "docs" / "note.md").write_text("later\n")
    _git(repo, "add", "-A")
    _git(repo, "commit", "-q", "-m", "move head")

    res = Res()
    checks.check_repo(res)
    entries = res.deploy_sync()
    if entries:
        _n, status, detail = entries[0]
        check("unresolvable revision -> WARN, not PASS", status == "WARN", f"{status}: {detail}")
        check("unresolvable revision -> says could not verify",
              "could not verify" in detail, detail)
    else:
        check("unresolvable revision -> reported", False, "no Deploy sync entry")


def test_matching_revision_still_passes():
    tmp = Path(tempfile.mkdtemp(prefix="deploysync-same-"))
    repo = _mk_repo(tmp)
    deployed = _git(repo, "rev-parse", "HEAD").stdout.strip()
    home = tmp / "deploy"
    _setup(tmp, deployed, home)

    res = Res()
    checks.check_repo(res)
    entries = res.deploy_sync()
    if entries:
        _n, status, detail = entries[0]
        check("HEAD == deployed revision -> PASS", status == "PASS", f"{status}: {detail}")
    else:
        check("HEAD == deployed revision -> reported", False, "no Deploy sync entry")


def main():
    tests = [v for k, v in sorted(globals().items())
             if k.startswith("test_") and callable(v)]
    for fn in tests:
        try:
            fn()
        except AssertionError as e:
            _FAIL.append(fn.__name__)
            print(f"  FAIL  {fn.__name__} — {e}")
        except Exception as e:  # noqa: BLE001
            _FAIL.append(fn.__name__)
            print(f"  FAIL  {fn.__name__} — {type(e).__name__}: {e}")
    print()
    if _FAIL:
        print(f"{len(_FAIL)} FAILED: {', '.join(_FAIL)}")
        raise SystemExit(1)
    print(f"ALL PASS ({len(tests)} cases)")


if __name__ == "__main__":
    main()
