#!/usr/bin/env python3
"""agent-deploy-drift-audit.py — no_agent drift-audit: deployed components vs repo source.

O5-S2 (HC gaps party 2026-08-21, roadmap F-008): scheduled drift-audit
assigned to the deployed-component-verification seam. Mirrors the on-demand
logic in cortex_doctor/checks.py (check_stale_deploys() + deploy-content
checks) so deployed-vs-repo drift is caught daily even when no commit,
doctor run, or cortex-update deploy happens that day.

Checks (identical semantics to the doctor's checks):
  1. register() source missing in the repo          -> FAIL (config drift)
  2. registered destination missing on disk         -> WARN (deploy gap)
  3. destination is a symlink to a registered path  -> INFO (intentional)
  4. destination is a symlink to an unknown target  -> WARN (should be a copy)
  5. deployed copy content differs from repo source -> FAIL (stale code)
     (SOURCE header stripped first — both header layouts, see _content_md5)
  6. orphan .py/.sh in ~/.hermes-cortex/scripts/ not in any register()
     mapping (non local-*, non preserve list)       -> WARN (stale deploy)

register_orch entries are only expected on orchestrator hosts (hostname
moses|esther or IS_ORCHESTRATOR=true), mirroring cortex-update.sh's
deployment gate.

Watchdog pattern (state-transition gate, same as the other no_agent
watchdogs):
  Empty stdout  -> silent (no drift, or unchanged since last alert)
  Text output   -> delivered to user (new/changed drift found or resolved)

Usage:
  python3 agent-deploy-drift-audit.py
  CORTEX_REPO=... CORTEX_HOME=... python3 agent-deploy-drift-audit.py

Exit codes: 0 = clean/silent, 1 = drift alert.
"""

from __future__ import annotations

import hashlib
import os
import re
import sys
from pathlib import Path

# state_tracker.py + hermes_tz.py live beside the script when deployed
# (~/.hermes-cortex/scripts/) and one level up when run from the repo
# (ops/scripts/health/). Resolve before importing them.
_HERE = Path(__file__).resolve().parent
for _candidate in (_HERE, _HERE.parent):
    if (_candidate / "state_tracker.py").exists():
        sys.path.insert(0, str(_candidate))
        break

from state_tracker import StateTracker  # noqa: E402
from hermes_tz import format_timestamp  # noqa: E402

CORTEX_REPO = Path(os.environ.get("CORTEX_REPO", str(Path.home() / "hermes-cortex")))
CORTEX_HOME = Path(os.environ.get("CORTEX_HOME", str(Path.home() / ".hermes-cortex")))

# Local-only no_agent cron scripts — deployed per-host, intentionally absent
# from register() mappings. Mirrors check_stale_deploys() + cortex-update.sh
# clean_stale_deploys().
PRESERVE = {
    "agent-daily-bible-reading.py",
    "local-clickhouse-log-cleanup.sh",
    "local-push-metrics.sh",
}


def _cron_ts(name: str) -> str:
    """Return non-LLM cron prefix: [YYYY-MM-DD HH:MM KST] <name>:"""
    kst = format_timestamp("[%Y-%m-%d %H:%M %Z]")
    return f"{kst} {name}:"


def _is_orch() -> bool:
    """Orchestrator hosts deploy register_orch entries (mirrors config.py)."""
    if os.environ.get("IS_ORCHESTRATOR", "").lower() in ("true", "1", "yes"):
        return True
    hostname = os.uname().nodename.split(".")[0]
    return hostname in ("moses", "esther")


def _md5(path: Path) -> str | None:
    try:
        if path.is_file():
            return hashlib.md5(path.read_bytes()).hexdigest()
    except (OSError, PermissionError):
        pass
    return None


def _content_md5(path: Path) -> str | None:
    """MD5 of file content with the cortex SOURCE header stripped.

    cortex-update.sh adds a 2-line SOURCE header + blank to deployed .sh/.py
    files. Since 2026-08-02 the header sits BELOW the shebang; legacy deployed
    files have the header at the top. Layouts stripped (identical to
    cortex_doctor/checks.py _content_md5):
      #!/usr/bin/env python3      <- shebang (kept)
      # SOURCE: <path>            <- dropped
      # Do NOT edit this file ... <- dropped
      (blank)                     <- dropped
    or legacy:
      # SOURCE: <path>            <- dropped
      # Do NOT edit this file ... <- dropped
      (blank)                     <- dropped
    """
    try:
        if not path.is_file():
            return None
        raw = path.read_bytes()
        text = raw.decode("utf-8", errors="surrogateescape")
        lines = text.splitlines(keepends=True)
        if len(lines) >= 4 and lines[0].startswith("#!") and lines[1].startswith("# SOURCE:") and "Do NOT edit" in lines[2]:
            content = "".join([lines[0]] + lines[4:])
        elif len(lines) >= 3 and lines[0].startswith("# SOURCE:") and "Do NOT edit" in lines[1]:
            content = "".join(lines[3:])
        else:
            content = text
        return hashlib.md5(content.encode("utf-8", errors="surrogateescape")).hexdigest()
    except (OSError, PermissionError):
        return None


def _parse_registrations(cortex_update: Path) -> list[tuple[str, str, Path, str]]:
    """Parse register()/register_orch() calls.

    Returns (kind, src_rel, dest, is_orch) tuples. register_orch entries are
    included so the caller can gate them on role.
    """
    out: list[tuple[str, str, Path, str]] = []
    try:
        content = cortex_update.read_text()
    except OSError:
        return out
    deploy_home_str = str(CORTEX_HOME)
    home_str = str(Path.home())
    for line in content.splitlines():
        line = line.strip()
        if not (line.startswith("register ") or line.startswith("register_orch ")) or line.startswith("#"):
            continue
        m = re.match(r'register(?:_orch)?\s+"([^"]+)"\s+"([^"]+)"', line)
        if not m:
            continue
        src_rel, dest_str = m.group(1), m.group(2)
        dest_str = dest_str.replace("${CORTEX_DEPLOY_HOME}", deploy_home_str)
        dest_str = dest_str.replace("${HOME}", home_str)
        kind = "register_orch" if line.startswith("register_orch ") else "register"
        out.append((kind, src_rel, Path(dest_str), dest_str))
    return out


def main() -> int:
    cortex_update = CORTEX_REPO / "ops" / "scripts" / "cortex-update.sh"
    if not cortex_update.exists():
        print(f"{_cron_ts('deploy-drift-audit')} cortex-update.sh not found at {cortex_update}")
        return 1

    orch = _is_orch()
    findings: list[tuple[str, str]] = []  # (severity, text)
    destinations: set[Path] = set()

    for kind, src_rel, dest, dest_str in _parse_registrations(cortex_update):
        is_orch_entry = kind == "register_orch"
        # Non-orch hosts never deploy register_orch entries — skip entirely.
        if is_orch_entry and not orch:
            continue
        destinations.add(dest)
        src = CORTEX_REPO / src_rel

        if not src.exists():
            findings.append(("FAIL", f"deploy source missing: {src_rel} -> {dest_str}"))
            continue
        if dest.is_symlink():
            resolved = dest.resolve()
            if resolved in destinations:
                # Intentional cortex-managed symlink (e.g. hook -> script).
                # Follows source updates automatically — no drift possible.
                continue
            findings.append(("WARN", f"deploy symlink to unknown target: {dest} -> {resolved} (should be a copy)"))
            continue
        if not dest.exists():
            findings.append(("WARN", f"deployed copy missing: {src_rel} -> {dest_str} (run cortex-update.sh)"))
            continue

        # Content drift: compare repo source vs deployed copy, tolerating the
        # SOURCE header cortex-update.sh prepends.
        src_md5 = _md5(src)
        dst_md5 = _md5(dest)
        if src_md5 is None or dst_md5 is None:
            continue
        if src_md5 == dst_md5:
            continue  # byte-identical
        if _content_md5(dest) == src_md5:
            continue  # matches after stripping SOURCE header
        findings.append(("FAIL", f"content drift: {dest} differs from repo source {src_rel} (run cortex-update.sh)"))

    # Orphan scan of the deployed scripts dir (mirrors check_stale_deploys).
    scripts_dir = CORTEX_HOME / "scripts"
    if scripts_dir.is_dir():
        for f in sorted(scripts_dir.rglob("*")):
            if not (f.is_file() and f.suffix in (".py", ".sh") and "__pycache__" not in str(f)):
                continue
            if f in destinations or f.name in PRESERVE or f.name.startswith("local-"):
                continue
            size = f.stat().st_size
            findings.append(("WARN", f"stale deploy (orphan): {f.relative_to(CORTEX_HOME)} — {size:,} bytes, not in any register() mapping"))

    if not findings:
        return 0  # clean — silent

    lines = [f"[{sev}] {txt}" for sev, txt in findings]
    msg = "\n".join(lines)
    fp = "|".join(sorted(txt for _, txt in findings))
    action = StateTracker("deploy-drift-audit").evaluate(fp, has_issues=True)
    if action == "silent":
        return 0

    print(f"{_cron_ts('deploy-drift-audit')} drift found ({len(findings)}):\n{msg}")
    return 1


if __name__ == "__main__":
    sys.exit(main())
