#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
#  Hermes Cortex — Multi-OS nginx Installer
#  Called by install.sh (server profile only).
# ─────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/os-config.sh"

GREEN="${GREEN:-'\033[0;32m'}"; YELLOW="${YELLOW:-'\033[1;33m'}"; RESET="${RESET:-'\033[0m'}"
info()  { printf "${GREEN}✓${RESET} %s\n" "$*"; }
warn()  { printf "${YELLOW}⚠${RESET} %s\n" "$*"; }

install_nginx() {
  if command -v nginx &>/dev/null; then
    info "nginx already installed — $(nginx -v 2>&1 || echo 'nginx')"
    return 0
  fi

  echo "  Installing nginx…"
  if [[ "$CORTEX_OS" == "macos" ]]; then
    brew install nginx
  elif [[ "$CORTEX_OS" == "linux" ]]; then
    $PKG_INSTALL nginx
  elif [[ "$CORTEX_OS" == "windows" ]]; then
    $PKG_INSTALL nginx
  fi
  info "nginx installed"
}

configure_nginx() {
  local langfuse_port="${1:-3000}"
  local dashboard_port="${2:-8901}"
  local listen_langfuse="${3:-13002}"
  local listen_dashboard="${4:-13001}"
  local config_file
  local nginx_conf

  if [[ "$CORTEX_OS" == "macos" ]]; then
    config_file="${NGINX_CONFIG_DIR}/hermes-services.conf"
    nginx_conf="${NGINX_CONFIG_DIR}/../nginx.conf"
    mkdir -p "$NGINX_CONFIG_DIR"
  elif [[ "$CORTEX_OS" == "linux" ]]; then
    config_file="${NGINX_CONFIG_DIR}/hermes-services.conf"
    nginx_conf="${NGINX_CONFIG_DIR}/nginx.conf"
    mkdir -p "$NGINX_CONFIG_DIR"
  else
    warn "nginx configuration not supported on Windows yet"
    return 0
  fi

  # Ensure zone-defs include file is installed alongside the main config
  local zone_defs_src="${SCRIPT_DIR}/../../install/deploy/nginx/hermes-zone-defs.conf"
  local zone_defs_dst="${NGINX_CONFIG_DIR}/../hermes-zone-defs.conf"
  if [[ -f "$zone_defs_src" && ! -f "$zone_defs_dst" ]]; then
    cp "$zone_defs_src" "$zone_defs_dst"
    info "  Installed hermes-zone-defs.conf"
  fi

  if [[ -f "$config_file" ]]; then
    info "nginx config already exists: ${config_file}"
    return 0
  fi

  # Try to deploy the hardened template from the repo (with OS path substitution)
  local hardened_template="${SCRIPT_DIR}/../../install/deploy/nginx/hermes-services.conf"
  if [[ -f "$hardened_template" ]]; then
    echo "  Deploying hardened nginx template from repo…"
    < "$hardened_template" subst_nginx_paths > "$config_file"
    info "  Created nginx config (hardened template, OS-aware paths)"
    return 0
  fi

  echo "  Creating nginx config: ${config_file}"
  cat > "$config_file" <<NGINXCONF
# Hermes reverse proxy — generated by hermes-cortex installer
# Local-only (no SSL). For production, add SSL certs.

upstream cortex_dashboard_backend {
    server 127.0.0.1:${dashboard_port};
}

upstream langfuse_backend {
    server 127.0.0.1:${langfuse_port};
}

# Cortex Dashboard — port ${listen_dashboard}
server {
    listen ${listen_dashboard};
    server_name localhost;

    location / {
        proxy_pass http://cortex_dashboard_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}

# Langfuse — port ${listen_langfuse}
server {
    listen ${listen_langfuse};
    server_name localhost;

    location / {
        proxy_pass http://langfuse_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_read_timeout 86400s;
    }
}
NGINXCONF
  info "  Created nginx config"
}

start_nginx() {
  if command -v nginx &>/dev/null; then
    if pgrep -x nginx > /dev/null; then
      if [[ "$CORTEX_OS" == "macos" ]]; then
        brew services restart nginx 2>&1 | tail -2
      elif [[ "$CORTEX_OS" == "linux" ]]; then
        sudo systemctl restart nginx
      fi
    else
      if [[ "$CORTEX_OS" == "macos" ]]; then
        brew services start nginx 2>&1 | tail -2
      elif [[ "$CORTEX_OS" == "linux" ]]; then
        sudo systemctl start nginx
      fi
    fi
    info "nginx started"
  fi
}

# ── Main ────────────────────────────────────────────────────
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_nginx
  configure_nginx "${2:-3000}" "${3:-8901}" "${4:-13002}" "${5:-13001}"
  start_nginx
fi
