#!/usr/bin/env bash
# SOURCE: /home/esther/hermes-cortex/ops/scripts/install/install-soft-session-cap.sh
# Do NOT edit this file — edit the source above and run: bash cortex-update.sh

# ───────────────────────────────────────────────────────────────
# install-soft-session-cap.sh
#
# O7-S2 (cost story c579ef95): converges ~/.hermes/config.yaml
# compression.threshold_tokens to the fleet's SOFT_SESSION_CAP_TOKENS
# convention — the "soft session cap": an ABSOLUTE token ceiling at
# which routine context compression kicks in, independent of the
# threshold ratio (compression.threshold is a fraction of context
# length; threshold_tokens overrides it with a hard token number).
#
# WHY SOFT (not a hard kill): compression preserves HEAD/TAIL/last-user
# turn verbatim (fact-retention eval, 6/6 PASS 2026-08-23) and emits a
# visible [CONTEXT SUMMARY] marker (compression.progress_notices: true,
# #52995) — never silent truncation. The cap prevents unbounded context
# growth on long interactive sessions (Titus ~70% of weekday spend;
# cache-killer long contexts) while keeping the session alive.
#
# VALUE SOURCE (priority): runtime env SOFT_SESSION_CAP_TOKENS >
# ~/hermes-cortex/.env (repo) > ~/.hermes-cortex/.env (deploy).
# UNSET = NO-OP: the script is safe to deploy fleet-wide BEFORE Luke
# picks the A/B value; it only writes when a value is explicitly set.
#
# A/B (2-week, Titus): esther = control (threshold ratio only), Titus =
# treatment (threshold_tokens set). The value itself is a Luke decision
# — this script is just the mechanism, delivered ahead of the decision.
#
# Idempotent: silent no-op when the current value already matches.
# No restart needed — the compressor reads config per session
# (conversation_compression.py / context_engine.py construct the
# ContextCompressor with the session's config).
# ───────────────────────────────────────────────────────────────
set -euo pipefail

HOME_DIR="${HOME:?}"
HERMES_HOME="${HERMES_HOME:-${HOME_DIR}/.hermes}"
CORTEX_DEPLOY_HOME="${CORTEX_DEPLOY_HOME:-${HOME_DIR}/.hermes-cortex}"

# ── Resolve the intended cap ─────────────────────────────────
# Priority: runtime env > ~/hermes-cortex/.env (repo) >
# ~/.hermes-cortex/.env (deploy). No fleet fallback: an unset cap is a
# valid state (control host / value not yet chosen) — NEVER invent one.
SOFT_SESSION_CAP_TOKENS="${SOFT_SESSION_CAP_TOKENS:-}"
if [[ -z "$SOFT_SESSION_CAP_TOKENS" && -f "${HOME_DIR}/hermes-cortex/.env" ]]; then
  SOFT_SESSION_CAP_TOKENS="$(grep -E '^SOFT_SESSION_CAP_TOKENS=' "${HOME_DIR}/hermes-cortex/.env" 2>/dev/null | tail -1 | cut -d= -f2- | tr -d '"' || true)"
fi
if [[ -z "$SOFT_SESSION_CAP_TOKENS" && -f "${CORTEX_DEPLOY_HOME}/.env" ]]; then
  SOFT_SESSION_CAP_TOKENS="$(grep -E '^SOFT_SESSION_CAP_TOKENS=' "${CORTEX_DEPLOY_HOME}/.env" 2>/dev/null | tail -1 | cut -d= -f2- | tr -d '"' || true)"
fi

if [[ -z "$SOFT_SESSION_CAP_TOKENS" ]]; then
  echo "install-soft-session-cap: SOFT_SESSION_CAP_TOKENS unset — no-op (control host or value pending)"
  exit 0
fi

# ── Validate: must be a positive integer (config_defaults clamps;
#    refuse garbage before it reaches the config file) ────────
if ! [[ "$SOFT_SESSION_CAP_TOKENS" =~ ^[0-9]+$ ]] || [[ "$SOFT_SESSION_CAP_TOKENS" -lt 1 ]]; then
  echo "install-soft-session-cap: invalid SOFT_SESSION_CAP_TOKENS '${SOFT_SESSION_CAP_TOKENS}' — refusing to apply" >&2
  exit 1
fi

HERMES_CMD=""
for candidate in hermes "${HERMES_HOME}/hermes-agent/venv/bin/hermes"; do
  if command -v "$candidate" &>/dev/null; then
    HERMES_CMD="$candidate"
    break
  fi
done

if [[ -z "$HERMES_CMD" ]]; then
  echo "install-soft-session-cap: no hermes CLI found — skipped" >&2
  exit 0
fi

# ── Read current value ───────────────────────────────────────
CURRENT=""
CURRENT="$("$HERMES_CMD" config get compression.threshold_tokens 2>/dev/null | tr -d '[:space:]' || true)"
CURRENT="${CURRENT:-<unset>}"

if [[ "$CURRENT" == "$SOFT_SESSION_CAP_TOKENS" ]]; then
  echo "install-soft-session-cap: compression.threshold_tokens already '${SOFT_SESSION_CAP_TOKENS}' — no change"
  exit 0
fi

echo "install-soft-session-cap: compression.threshold_tokens '${CURRENT}' → '${SOFT_SESSION_CAP_TOKENS}'"

# ── Apply via hermes config set (canonical path, no hand-editing) ──
"$HERMES_CMD" config set compression.threshold_tokens "$SOFT_SESSION_CAP_TOKENS" >/dev/null 2>&1 || true

# ── Verify what actually landed (read back from the file, not the tool) ──
APPLIED=""
if command -v python3 &>/dev/null; then
  APPLIED="$(python3 -c "
import yaml, sys
try:
    c = yaml.safe_load(open('${HERMES_HOME}/config.yaml'))
    comp = c.get('compression') or {}
    v = comp.get('threshold_tokens')
    print(v if v is not None else '')
except Exception:
    print('')
" 2>/dev/null || echo "")"
fi

if [[ -n "$APPLIED" && "$APPLIED" == "$SOFT_SESSION_CAP_TOKENS" ]]; then
  echo "install-soft-session-cap: verified config.yaml compression.threshold_tokens = ${APPLIED}"
else
  echo "install-soft-session-cap: WARNING — expected '${SOFT_SESSION_CAP_TOKENS}', read back '${APPLIED:-<unset>}'" >&2
  echo "  config.yaml may be managed elsewhere; check ${HERMES_HOME}/config.yaml compression.threshold_tokens" >&2
  exit 1
fi
