#!/usr/bin/env python3
"""Extract langfuse env vars from the stopped container and write .env file."""
import json, subprocess, os, sys

result = subprocess.run(
    ['docker', 'inspect', 'langfuse-langfuse-web-1'],
    capture_output=True, text=True
)
try:
    data = json.loads(result.stdout)
except (json.JSONDecodeError, IndexError):
    print("ERROR: Could not inspect langfuse-langfuse-web-1")
    sys.exit(1)

env = {}
for e in data[0]['Config']['Env']:
    if '=' in e:
        k, v = e.split('=', 1)
        env[k] = v

# Map docker env -> compose env var names
mapping = {
    'CLICKHOUSE_PASSWORD': 'LANGFUSE_CLICKHOUSE_PASSWORD',
    'REDIS_AUTH': 'LANGFUSE_REDIS_AUTH',
    'MINIO_ACCESS_KEY': 'LANGFUSE_MINIO_ACCESS_KEY',
    'MINIO_SECRET_KEY': 'LANGFUSE_MINIO_SECRET_KEY',
    'SALT': 'LANGFUSE_SALT',
    'SECRET_KEY': 'LANGFUSE_SECRET_KEY',
    'LANGFUSE_ENCRYPTION_KEY': 'LANGFUSE_ENCRYPTION_KEY',
}

# Also check for exact compose env names
needed = list(mapping.values()) + ['LANGFUSE_NEXTAUTH_SECRET', 'LANGFUSE_POSTGRES_PASSWORD']
env_lines = []
for compose_key in needed:
    # First try direct match
    val = env.get(compose_key)
    if val:
        env_lines.append(f'{compose_key}={val}')
        continue
    # Then try docker_key mapping
    for docker_key, ck in mapping.items():
        if ck == compose_key:
            val = env.get(docker_key)
            if val:
                env_lines.append(f'{compose_key}={val}')
                break
    else:
        # Check if it's in the container env under NEXTAUTH_URL -> but we need NEXTAUTH_SECRET
        print(f"WARNING: Could not find {compose_key}", file=sys.stderr)

# Also check POSTGRES_PASSWORD
if 'POSTGRES_PASSWORD' in env:
    env_lines.append(f'LANGFUSE_POSTGRES_PASSWORD={env["POSTGRES_PASSWORD"]}')
elif 'POSTGRES_PASSWORD' not in env:
    # Default from compose
    env_lines.append('LANGFUSE_POSTGRES_PASSWORD=postgres')

# Write .env file
output_path = os.path.expanduser('~/Developer/AI/hermes-cortex/deploy/.env')
with open(output_path, 'w') as f:
    f.write('# Langfuse environment variables (auto-recovered from stopped container)\n')
    f.write('# Generated by auto-remediation at ' + subprocess.run(['date'], capture_output=True, text=True).stdout.strip() + '\n')
    f.write('\n'.join(env_lines) + '\n')

print(f"Wrote {len(env_lines)} env vars to {output_path}")
for line in env_lines:
    k = line.split('=', 1)[0]
    print(f"  {k}: {'*' * 8}")
