#!/usr/bin/env python3
"""Did the work actually LAND? Verify mechanically — or say COULD NOT VERIFY.

WHY THIS EXISTS
---------------
An operational cycle ("deploy + push") can NEVER carry committed evidence of its own
success. The push happens last, so a transcript of it can only be written afterwards; that
commit changes the tip, which invalidates the review receipt, which blocks the push, which
the doctor's Deploy sync flags because the deployed tree now trails the commit. The result is
a loop: commit evidence -> new tip -> close again -> commit more evidence. Reviewers are
right to demand committed evidence, and the fleet's own ordering rules keep destroying it.

The way out is not a transcript but a RE-RUNNABLE CHECK, committed BEFORE the push, that a
later reviewer can execute against the state that exists after it. This is that check:

  1. a receipt exists for the tip AND authorises THIS range (tip + base), validated by
     ops/scripts/lib/review-receipt-check.py — the same script the push gate runs. Only
     required when the range touches a path in ops/scripts/lib/always-review-paths.txt,
     exactly as the gate scopes it; a range that touches none reports "not required"
     rather than a COULD NOT VERIFY that would be a false alarm.
  2. every file the range changed that has a deploy-map entry MATCHES its deployed copy
     (this is what a doctor "Deploy sync" measures, named file by file here)
  3. origin/<branch> equals the tip (unless --no-remote)

EXIT CODES
    0  every check passed
    1  a check FAILED — a real mismatch, named with both hashes/paths
    2  COULD NOT VERIFY — an input could not be read; never reported as a pass

USAGE
    verify-landed.py [--repo PATH] [--branch main] [--base REV] [--tip REV]
                     [--manifest PATH] [--receipt-dir PATH] [--no-remote]
"""
import argparse
import hashlib
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

_FAIL = "FAIL "
_PASS = "PASS "
_CANNOT = "COULD NOT VERIFY"


def _git(repo, *args):
    result = subprocess.run(["git", "-C", str(repo), *args],
                            capture_output=True, text=True)
    return result.returncode, result.stdout.strip(), result.stderr.strip()


def _sha256(path):
    try:
        return hashlib.sha256(Path(path).read_bytes()).hexdigest()
    except OSError:
        return None


_DEPLOY_HEADER_LINES = 3


def _deployed_hash(path):
    """Hash a DEPLOYED file's BODY, without the deploy header.

    Deployed copies carry a header the deploy inserts — ``# SOURCE: <repo path>`` and
    ``# Do NOT edit this file`` — and it goes AFTER the shebang, not at the very top. So a
    raw hash never matches (a false FAIL for every registered text file), and neither does
    blindly dropping the first N lines. Remove the header LINES, wherever in the first few
    they sit; hash what remains. A probe must know the shape of the thing it checks.
    """
    try:
        data = Path(path).read_bytes()
    except OSError:
        return None
    kept = []
    index = 0
    lines = data.split(b"\n")
    while index < len(lines):
        upper = lines[index].upper()
        if index < 5 and (upper.startswith(b"# SOURCE:") or upper.startswith(b"# DO NOT EDIT")):
            index += 1
            # The header block is closed by a blank line; drop that too, or the body keeps
            # an extra blank and the hash never matches (4477 lines vs 4476).
            if index < len(lines) and lines[index].strip() == b"":
                index += 1
            continue
        kept.append(lines[index])
        index += 1
    return hashlib.sha256(b"\n".join(kept)).hexdigest()


def _sibling(name):
    """Import a sibling script in this directory (one implementation, not two)."""
    candidate = Path(__file__).resolve().parent / name
    if not candidate.is_file():
        return None
    spec = importlib.util.spec_from_file_location(name.replace("-", "_"), candidate)
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_ALWAYS_REVIEW_REL = "ops/scripts/lib/always-review-paths.txt"
_RECEIPT_CHECK_REL = "ops/scripts/lib/review-receipt-check.py"


def _always_review_patterns(repo):
    """The gate's OWN list of always-review prefixes. None = unreadable (fail closed)."""
    try:
        text = (repo / _ALWAYS_REVIEW_REL).read_text(encoding="utf-8")
    except OSError:
        return None
    return [line.strip() for line in text.splitlines()
            if line.strip() and not line.strip().startswith("#")]


def _receipt_authorises(repo, receipt_path, tip, base):
    """Validate a receipt through the SAME validator the push gate uses.

    Returns True/False, or None when the validator cannot be run — because a second,
    looser implementation of this rule is how a receipt earned for one range comes to
    authorise another.
    """
    checker = repo / _RECEIPT_CHECK_REL
    if not checker.is_file():
        return None
    try:
        proc = subprocess.run([sys.executable, str(checker), str(receipt_path), tip, base],
                              capture_output=True, text=True, timeout=60)
    except (OSError, subprocess.SubprocessError):
        return None
    return proc.stdout.strip() == "1"


def main() -> int:
    ap = argparse.ArgumentParser(description="Verify that a change actually landed.")
    ap.add_argument("--repo", default=".")
    ap.add_argument("--branch", default="main")
    ap.add_argument("--base", default=None, help="default: merge-base with origin/<branch>")
    ap.add_argument("--tip", default=None, help="default: HEAD")
    ap.add_argument("--manifest", default=None)
    ap.add_argument("--receipt-dir", default=None)
    ap.add_argument("--no-remote", action="store_true",
                    help="skip check 3 (for a repo with no remote configured)")
    args = ap.parse_args()

    repo = Path(args.repo).resolve()
    if not (repo / ".git").exists():
        print(f"{_CANNOT}: {repo} is not a git checkout. Nothing was checked.")
        return 2

    rc, tip, _ = _git(repo, "rev-parse", "HEAD" if args.tip is None else args.tip)
    if rc != 0:
        print(f"{_CANNOT}: cannot resolve the tip revision. Nothing was checked.")
        return 2
    if args.base is None:
        rc, base, _ = _git(repo, "merge-base", f"origin/{args.branch}", "HEAD")
        if rc != 0:
            print(f"{_CANNOT}: cannot compute a base (no origin/{args.branch}?). "
                  f"Pass --base. Nothing was checked.")
            return 2
    else:
        base = args.base
    print(f"# range: {base[:12]}..{tip[:12]}  repo: {repo}")

    failed = False
    unverified = []

    # ── 1. the review receipt — required only for an ALWAYS-REVIEW range ─────
    # Mirror the gate (ops/scripts/pre-push-pull): it demands a receipt only when the
    # range touches a path in ops/scripts/lib/always-review-paths.txt. Demanding one
    # unconditionally reports a legitimately unreviewed docs-only push as COULD NOT
    # VERIFY — a false alarm, and the reason this check was fixed. The mirror is also
    # COMPLETE: the receipt is validated by the same script the gate runs, so a receipt
    # earned for a different range is refused here too.
    _, range_names, _ = _git(repo, "diff", "--name-only", f"{base}..{tip}")
    changed = [n for n in range_names.splitlines() if n.strip()]
    receipt_dir = Path(args.receipt_dir) if args.receipt_dir else Path.home() / ".hermes-cortex" / "state"
    slug = repo.name
    patterns = _always_review_patterns(repo)
    if patterns is None:
        unverified.append(f"receipt: cannot read {_ALWAYS_REVIEW_REL}, so whether this "
                          f"range needs one is unknown")
        print(f"{_CANNOT}: {_ALWAYS_REVIEW_REL} is unreadable; the receipt requirement "
              f"was NOT evaluated.")
    else:
        always = [n for n in changed if any(p in n for p in patterns)]
        if not always:
            print(f"{_PASS} receipt: not required — {base[:12]}..{tip[:12]} touches no "
                  f"always-review path")
        else:
            receipt_path = receipt_dir / f".reviewed-{slug}-{tip}.json"
            if not receipt_path.is_file():
                unverified.append(f"receipt: {receipt_path} does not exist (this range "
                                  f"touches an always-review path: {', '.join(always)})")
                print(f"{_CANNOT}: receipt {receipt_path} is absent, and this range "
                      f"touches an always-review path: {', '.join(always)}")
            else:
                verdict = None
                try:
                    verdict = json.loads(receipt_path.read_text()).get("verdict")
                except (OSError, json.JSONDecodeError) as exc:
                    unverified.append(f"receipt: unreadable ({exc})")
                    print(f"{_CANNOT}: receipt {receipt_path} is unreadable: {exc}")
                else:
                    authorises = _receipt_authorises(repo, receipt_path, tip, base)
                    if authorises is None:
                        unverified.append(f"receipt: cannot run {_RECEIPT_CHECK_REL}")
                        print(f"{_CANNOT}: {_RECEIPT_CHECK_REL} is unavailable, so the "
                              f"receipt could NOT be validated.")
                    elif authorises:
                        print(f"{_PASS} receipt: {receipt_path.name} verdict=CLEAN "
                              f"(bound to {base[:12]}..{tip[:12]})")
                    else:
                        failed = True
                        print(f"{_FAIL} receipt: {receipt_path.name} verdict={verdict!r} "
                              f"does not authorise {base[:12]}..{tip[:12]} "
                              f"(not CLEAN, or bound to a different range)")

    # ── 2. is the DEPLOYED tree current with the range? ──────────────────────
    dp = _sibling("deployed-path.py")
    if dp is None:
        unverified.append("deployed tree: deployed-path.py not found beside this script")
        print(f"{_CANNOT}: deployed-path.py is not beside this script; the deployed tree "
              f"was NOT checked.")
    else:
        manifest = dp._find_manifest(args.manifest)
        if manifest is None or not manifest.is_file():
            unverified.append("deployed tree: no deploy-manifest.tsv found")
            print(f"{_CANNOT}: no deploy-manifest.tsv found; the deployed tree was NOT checked.")
        else:
            read_manifest = dp._load_read_manifest()
            if read_manifest is None:
                unverified.append("deployed tree: cannot import cortex_lib.paths.read_manifest")
                print(f"{_CANNOT}: cannot read the deploy map; the deployed tree was NOT checked.")
            else:
                mapping = read_manifest(manifest)
                registered = [n for n in changed if n in mapping]
                for name in changed:
                    if name not in mapping:
                        continue
                    repo_hash = _sha256(repo / name)
                    deployed_hash = _deployed_hash(mapping[name])
                    if repo_hash is None or deployed_hash is None:
                        unverified.append(f"deployed tree: {name} unreadable on one side")
                        print(f"{_CANNOT}: {name} — repo={repo_hash} deployed={deployed_hash} "
                              f"({mapping[name]})")
                    elif repo_hash == deployed_hash:
                        print(f"{_PASS} deployed: {name} matches {mapping[name]}")
                    else:
                        failed = True
                        print(f"{_FAIL} deployed: {name} repo={repo_hash[:12]} "
                              f"deployed={deployed_hash[:12]} — deploy the tip, then re-run")
                print(f"# {len(registered)} of {len(changed)} changed files are deployed sources; "
                      f"{len(mapping)} entries in the map")

    # ── 3. is the tip actually on the remote? ────────────────────────────────
    if args.no_remote:
        print("# remote sync: skipped (--no-remote)")
    else:
        rc, _, err = _git(repo, "fetch", "-q", "origin", args.branch)
        if rc != 0:
            unverified.append(f"remote sync: fetch failed ({err})")
            print(f"{_CANNOT}: cannot fetch origin/{args.branch}: {err}")
        else:
            rc, remote_tip, _ = _git(repo, "rev-parse", f"origin/{args.branch}")
            if rc != 0:
                unverified.append("remote sync: cannot resolve origin/<branch>")
                print(f"{_CANNOT}: cannot resolve origin/{args.branch}.")
            elif remote_tip == tip:
                print(f"{_PASS} remote: origin/{args.branch} == {tip[:12]}")
            else:
                failed = True
                print(f"{_FAIL} remote: origin/{args.branch}={remote_tip[:12]} but tip={tip[:12]}")

    print()
    if failed:
        print("FAILED — a check above is false. Fix it and re-run; this is a real mismatch.")
        return 1
    if unverified:
        print(f"{_CANNOT} — {len(unverified)} check(s) could not be run: " + "; ".join(unverified))
        print("A partial check is not a pass. Nothing above was assumed.")
        return 2
    print("All checks passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
