#!/usr/bin/env bash
# run-cutover-evidence.sh — re-runnable evidence for the gateway cutover guards.
#
# The adversarial gate is right to refuse a claim it cannot re-run: "proven under
# real systemd" is a sentence, not evidence. This script PRODUCES the evidence, so
# any reviewer can execute it and get the same answers.
#
# It checks, in order:
#   1. the guard REFUSES the production config (the live bot's token_ref)
#   2. the guard ALLOWS the second-bot config (a distinct token)
#   3. under REAL systemd, a throwaway probe unit is FAILED by the guard
#   4. the poll offset round-trips through a real TelegramAdapter
#   5. the test suite result, with the exact counts
#   6. the live bot's MainPID is unchanged and every enforcement target is locked
#
# Exit: 0 = every check passed. Non-zero = the first failing check's status.
# Usage: bash run-cutover-evidence.sh [output-file]
set -uo pipefail

REPO="${REPO:-$HOME/hermes-cortex}"
DEPLOY="${CORTEX_DEPLOY_HOME:-$HOME/.hermes-cortex}"
OUT="${1:-$REPO/docs/evidence/gateway-cutover-evidence.md}"
GUARD="$DEPLOY/scripts/cortex_gateway/guard_distinct_token.py"
PROD_CONFIG="$DEPLOY/gateway.yaml"
SECOND_CONFIG="$DEPLOY/gateway-esther0001.yaml"
PROBE_UNIT="$HOME/.config/systemd/user/cortex-gateway-guard-probe.service"

FAILED=0
declare -a LINES=()

_say() { printf '%s\n' "$*" | tee -a "$OUT" >/dev/null; printf '%s\n' "$*"; }
_check() {  # _check <ok:0|1> <description>
  if [[ "$1" -eq 0 ]]; then LINES+=("PASS  $2"); else LINES+=("FAIL  $2"); FAILED=1; fi
}

: > "$OUT"
_say "# Gateway cutover — evidence"
_say ""
_say "Generated by \`ops/scripts/cortex_gateway/run-cutover-evidence.sh\` on $(date -u '+%Y-%m-%dT%H:%M:%SZ') (UTC)."
_say "Re-run it to reproduce every line below."
_say ""

# ── 1 + 2: the guard, both directions, against the REAL configs ──────
_say "## 1-2. The live-token guard, both directions"
_say ""
_say '```'
# The canonical env holds the tokens; the guard reads them from the environment,
# exactly as systemd passes them via EnvironmentFile.
set -a
# shellcheck disable=SC1091
[[ -f "$REPO/.env" ]] && . "$REPO/.env"
set +a

PROD_OUT="$(/usr/bin/python3 "$GUARD" "$PROD_CONFIG" 2>&1)"; PROD_RC=$?
_say "\$ guard_distinct_token.py gateway.yaml        # production = the LIVE bot"
_say "$PROD_OUT"
_say "exit=$PROD_RC   (expected: non-zero, REFUSING TO START)"
_say ""
SECOND_OUT="$(/usr/bin/python3 "$GUARD" "$SECOND_CONFIG" 2>&1)"; SECOND_RC=$?
_say "\$ guard_distinct_token.py gateway-esther0001.yaml   # second bot"
_say "$SECOND_OUT"
_say "exit=$SECOND_RC   (expected: 0, distinct)"
_say '```'
_say ""
[[ $PROD_RC -ne 0 ]] && _check 0 "guard REFUSES the production config (exit $PROD_RC)" \
                     || _check 1 "guard refused the production config — IT ALLOWED THE LIVE TOKEN"
[[ $SECOND_RC -eq 0 ]] && _check 0 "guard ALLOWS the second-bot config (exit 0)" \
                       || _check 1 "guard blocked the second-bot config (exit $SECOND_RC)"

# ── 3: real systemd fails the unit ───────────────────────────────────
_say "## 3. Real systemd refuses the unit (ExecStartPre)"
_say ""
if command -v systemctl >/dev/null 2>&1 && [[ -d "$HOME/.config/systemd/user" ]]; then
  cat > "$PROBE_UNIT" <<PROBE
# THROWAWAY probe written by run-cutover-evidence.sh — removed at the end.
# Points the SAME guard at the PRODUCTION config, which must be refused, so this
# unit must FAIL to start. ExecStart is /bin/true so only the guard can fail.
[Unit]
Description=THROWAWAY probe — the live-token guard must fail this unit
[Service]
Type=oneshot
EnvironmentFile=-%h/hermes-cortex/.env
ExecStartPre=/usr/bin/python3 %h/.hermes-cortex/scripts/cortex_gateway/guard_distinct_token.py %h/.hermes-cortex/gateway.yaml
ExecStart=/bin/true
PROBE
  systemctl --user daemon-reload >/dev/null 2>&1
  systemctl --user start cortex-gateway-guard-probe.service >/dev/null 2>&1
  PROBE_RC=$?
  PROBE_STATE="$(systemctl --user show cortex-gateway-guard-probe.service -p ActiveState -p ExecMainStatus --value 2>/dev/null | tr '\n' ' ')"
  PROBE_JOURNAL="$(journalctl --user -u cortex-gateway-guard-probe.service --no-pager -n 20 2>/dev/null | grep -m1 'guard:' || echo '(no guard line)')"
  rm -f "$PROBE_UNIT"
  systemctl --user daemon-reload >/dev/null 2>&1
  systemctl --user reset-failed cortex-gateway-guard-probe.service >/dev/null 2>&1
  _say '```'
  _say "\$ systemctl --user start cortex-gateway-guard-probe.service"
  _say "start exit=$PROBE_RC   (expected: non-zero)"
  _say "unit state: $PROBE_STATE"
  _say "journal   : $PROBE_JOURNAL"
  _say '```'
  _say ""
  [[ $PROBE_RC -ne 0 ]] && _check 0 "systemd FAILED the unit on the guard's refusal (exit $PROBE_RC)" \
                        || _check 1 "systemd STARTED the unit — the guard did not block it"
else
  _say "_skipped: no systemd user session here._"
fi

# ── 4: the offset round-trips ────────────────────────────────────────
_say "## 4. The poll offset round-trips through a real adapter"
_say ""
_say '```'
OFFSET_OUT="$(cd "$REPO/ops/scripts" && /usr/bin/python3 - <<'PY' 2>&1
import tempfile, json
from pathlib import Path
import cortex_gateway.transport as T
with tempfile.TemporaryDirectory() as tmp:
    p = Path(tmp) / "state" / "gateway-offset.json"
    a = T.TelegramAdapter(token="t", initial_offset=0, state_path=p)
    a.set_offset(4242)
    b = T.TelegramAdapter(token="t", initial_offset=0, state_path=p)   # a fresh process
    print(f"persisted file : {json.loads(p.read_text())}")
    print(f"resumed offset : {b.offset}  (expected 4242)")
    a.set_offset(50)                                                  # a stale call
    print(f"after stale 50 : {a.offset}  (expected 4242 — monotonic)")
PY
)"; OFFSET_RC=$?
_say "$OFFSET_OUT"
_say '```'
_say ""
grep -q "resumed offset : 4242" <<<"$OFFSET_OUT" \
  && _check 0 "offset persisted and resumed at 4242" \
  || _check 1 "offset did NOT round-trip"

# ── 5: the test suite ────────────────────────────────────────────────
_say "## 5. Test suite"
_say ""
_say '```'
TESTS="tests/test_gateway_cutover_guards.py tests/test_repo_resource_paths.py
tests/test_deploy_marker_guard.py tests/test_gateway_modules_are_deployed.py
tests/test_cortex_gateway_daemon.py tests/test_cortex_gateway_transport.py
tests/test_gateway_pairing.py"
_PYTEST_LOG="$(mktemp)"
(cd "$REPO" && "${PYTEST_PY:-$(command -v python3)}" -m pytest $TESTS -q > "$_PYTEST_LOG" 2>&1)
TEST_RC=$?                                  # the subshell's status — NOT tail's
TEST_OUT="$(tail -3 "$_PYTEST_LOG")"
rm -f "$_PYTEST_LOG"
_say "\$ pytest <7 files> -q"
_say "$TEST_OUT"
_say '```'
_say ""
[[ $TEST_RC -eq 0 ]] && _check 0 "test suite green" || _check 1 "test suite RED"

# ── 6: the live bot is untouched, the gate is locked ─────────────────
_say "## 6. Live bot untouched, enforcement locked"
_say ""
_say '```'
LIVE_PID="$(systemctl --user show hermes-gateway.service -p MainPID --value 2>/dev/null)"
SECOND_STATE="$(systemctl --user is-active cortex-gateway-esther0001.service 2>/dev/null)"
LOCKED="$(hermes-plugin-lock status 2>/dev/null | grep -c '^----i')"
UNLOCKED="$(hermes-plugin-lock status 2>/dev/null | grep -vc '^----i')"
_say "hermes-gateway.service (LIVE) MainPID : ${LIVE_PID:-<not running>}"
_say "cortex-gateway-esther0001.service     : ${SECOND_STATE:-<unknown>}"
_say "enforcement targets locked            : $LOCKED"
_say "enforcement targets unlocked          : $UNLOCKED   (expected 0)"
_say '```'
_say ""
[[ "${LIVE_PID:-0}" != "0" ]] && _check 0 "live bot still running (MainPID $LIVE_PID)" \
                              || _check 1 "live bot is NOT running"
[[ "$UNLOCKED" == "0" ]] && _check 0 "every enforcement target locked ($LOCKED)" \
                         || _check 1 "$UNLOCKED enforcement target(s) UNLOCKED"

# ── summary ──────────────────────────────────────────────────────────
_say "## Summary"
_say ""
for line in "${LINES[@]}"; do _say "- \`$line\`"; done
_say ""
if [[ $FAILED -eq 0 ]]; then
  _say "**All checks passed.**"
else
  _say "**FAILURES PRESENT — do not treat this change as verified.**"
fi
_say ""
_say "Written to \`${OUT#"$REPO"/}\`."
exit $FAILED
