#!/usr/bin/env python3
"""generate-bus-wrappers.py — Generate per-agent bus watch wrappers.

Reads agent-registry.json and creates wrapper scripts
for each agent with bus monitoring enabled.

Usage:
    python3 generate-bus-wrappers.py              # generate all wrappers
    python3 generate-bus-wrappers.py --apply-crons  # generate + create cron jobs
    python3 generate-bus-wrappers.py --dry-run      # show what would be created
"""
import json
import os
import stat
import subprocess
import sys
from pathlib import Path

HOME = Path.home()
STATE_DIR = HOME / ".hermes" / "state"
SCRIPTS_DIR = HOME / ".hermes" / "scripts"
REGISTRY_PATH = STATE_DIR / "agent-registry.json"

BUS_WATCH_TEMPLATE = """#!/usr/bin/env bash
# Bus watch wrapper for {agent_name}
# Generated by generate-bus-wrappers.py
export AGENT_NAME="{agent_name}"
export AGENT_BUS_URL="{bus_url}"
export AGENT_BUS_TOKEN="{bus_token}"
exec ~/.hermes/scripts/agent-bus-monitor.sh "$@"
"""


def main() -> int:
    dry_run = "--dry-run" in sys.argv
    apply_crons = "--apply-crons" in sys.argv

    if not REGISTRY_PATH.exists():
        print("No agent registry found", file=sys.stderr)
        return 1

    registry = json.loads(REGISTRY_PATH.read_text())
    agents = registry.get("agents", {})
    bus_url = os.environ.get("AGENT_BUS_URL", "http://localhost:8903")
    bus_token = os.environ.get("AGENT_BUS_TOKEN", "")

    token_file = HOME / ".hermes" / "state" / "bus.token"
    if not bus_token and token_file.exists():
        bus_token = token_file.read_text().strip()

    created = 0
    for name, cfg in agents.items():
        if not cfg.get("bus_monitor", True):
            continue
        wrapper_path = SCRIPTS_DIR / f"bus-watch-{name}.sh"
        content = BUS_WATCH_TEMPLATE.format(
            agent_name=name,
            bus_url=bus_url,
            bus_token=bus_token,
        )
        if dry_run:
            print(f"  Would create: {wrapper_path}")
        else:
            wrapper_path.write_text(content)
            wrapper_path.chmod(wrapper_path.stat().st_mode | stat.S_IEXEC)
            print(f"  Created: {wrapper_path}")
        created += 1

    if apply_crons and not dry_run:
        for name in agents:
            cfg = agents[name]
            schedule = cfg.get("bus_watch_schedule", "every 10m")
            deliver = cfg.get("bus_deliver", "local")
            wrapper = f"bus-watch-{name}.sh"
            subprocess.run([
                "hermes", "cron", "create",
                "--name", f"bus-watch-{name}",
                "--schedule", schedule,
                "--script", wrapper,
                "--no-agent",
                "--deliver", deliver,
            ], capture_output=True, timeout=15)
            print(f"  Cron created: bus-watch-{name} ({schedule})")

    print(f"Done: {created} wrapper(s)")
    return 0


if __name__ == "__main__":
    main()
